### ISSUE TITLE
Subtitles doesn't sync when seeking

### ISSUE THREAD

**Issue by vlad88sv** [popcorntime/popcorntime#1500] opened 2020-05-31 16:50 UTC
Operating System Version:
> Operating System: Kubuntu 20.04
> KDE Plasma Version: 5.18.5
> KDE Frameworks Version: 5.68.0
> Qt Version: 5.12.8
> Kernel Version: 5.6.14-050614-generic
> OS Type: 64-bit
> Processors: 4 × Intel® Core™ i5-3210M CPU @ 2.50GHz
> Memory: 15.5 GiB of RAM

Popcorn Time Version:
0.4.4-linux64

Download date:
May 30, 2020

Download url (optional):
https://mirror02.popcorntime.app/build/Popcorn-Time-0.4.4-linux64.zip

#### Expected Behaviour
When you seek in the video I expect the subtitles to remain on-sync
...

#### Actual Behaviour
After seek by clicking the progress bar the subtitles continue playing in a random position.
If you change language they are fine, if you seek again they become wrong again
...

#### Steps to reproduce the behaviour

1. Play a video with subtitles, ensure that they are synced - don't seek
2. Click anywhere on the progress bar, subtitles are wrong after that
3. Change subtitle language, they will be synced

Note: this doesn't seem to be an issue if you seek with the keyboard arrows.

#### Screenshot of error from developer console (optional)
-

**Comment by kiriles90** [comment] 2020-10-09 05:52
@vlad88sv have you tried the latest dev build from ci.popcorntime.app? does this issue still exist?

**Comment by vlad88sv** [comment] 2020-10-09 14:25
I'll try and report back, haven't used it ever since due to this bug

**Comment by kiriles90** [comment] 2020-10-26 15:09
I've tried in several occasions and tbh I was never able to reproduce this.

@Persei08 maybe close it for now if you cant reproduce it either

**Comment by dutchy1001** [comment] 2020-10-26 18:34
I can't reproduce this either on Win10 machine

**Comment by Persei08** [comment] 2020-10-26 18:55
Tried on development branch (commit: d5480e456e887972a12c4d2d6ca90b28e20bb390) on xubuntu 20.04 with movies 
- "Hard Kill" 720p, English and English2 subs
- "Bill & Ted Face the Music" 720p, Français (french) and Français2 subs

cannot reproduce.

@vlad88sv can you test again with [latest dev build](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/) and provides movie title and subtitles languages with which it happen plz.

**Comment by Persei08** [comment] 2020-10-28 13:56
ok, i close this one, will reopen eventually if we have more infos and can confirm the issue

**Closed as completed by Persei08** 2020-10-28 13:56 UTC
