### ISSUE TITLE
search

### ISSUE THREAD

**Issue by Majesty-cmd** [popcorntime/popcorntime#1514] opened 2020-06-07 06:16 UTC
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Majesty-cmd** [comment] 2020-06-07 06:21
Hey. the search bar it's not working well!!!
1st i just open the movie Les Misérables and it wasn't the movie wanted to watch so i wrote the name in the search bar and the result was No movie found.
Will be the pics who show u the problem

![capture_001_07062020_071029](https://user-images.githubusercontent.com/63502767/83961820-e50edb80-a88e-11ea-8771-ffff0671fcbb.jpg)
![capture_002_07062020_071059](https://user-images.githubusercontent.com/63502767/83961825-f0620700-a88e-11ea-828d-1feacf1ec887.jpg)

**Comment by dutchy1001** [comment] 2020-06-07 19:12
When you open a new issue there are some things to fill in so they can correctly determent were the issue might be, as you failed to do so it will be hard to see how this issue will be fixed.

Before making an issue it's always best to update to the latest build to see if that will fix your issue, you can find this build **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/424/)**.
If the problem is still there give them the info needed as the first post indicates.

**Closed as completed** 2020-09-23 00:29 UTC
