### ISSUE TITLE
VPN prevents "connect to opensubtitles.org" to function correctly

### ISSUE THREAD

**Issue by natbusa** [popcorntime/popcorntime#1674] opened 2020-09-05 16:58 UTC
Operating System Version:
Linux

Popcorn Time Version:
https://github.com/popcorn-official/popcorn-desktop/commit/b4b2792bbf1c8e25c61cb1a2e460b033f9e36cb4

Download date:
2020-09-06

Download url (optional):
https://github.com/popcorn-official/popcorn-desktop/

#### Expected Behaviour
Connect to www.opensubtitles.org while running VPN (expressVPN)...

#### Actual Behaviour
Doesn't connect with correct login data ...

#### Steps to reproduce the behaviour
Enable VPN. connect to opensubtitle button will not work even with correct credentials

**Comment by natbusa** [comment] 2020-09-05 16:58
workaround: connect to opensubtitles without VPN, then switch the vpn back on.

Additional notes: 
Apparently the problem is only there during connection, but not during subtitles search/download. 
So once you connect, all is good. If your connectivity token expires repeat the process.

**Comment by natbusa** [comment] 2020-09-05 17:20
Possible root cause:
in `src/app/lib/views/settings_container.js`
```
OpenSubtitles.login()
```
might fail under VPN
I am not sure if this is a opensubtitles.org or a popcorn time issue

**Comment by pcenta** [comment] 2020-09-05 18:23
Probable reason: [LINK](https://forum.opensubtitles.org/viewtopic.php?t=16377)

**Comment by Persei08** [comment] 2020-09-07 14:28
Can someone try to reproduce and check the error messages in console (F12 key > "console" tab), and paste them here ?

I tried with 2 differents vpn but failed to reproduce :/

**Comment by dutchy1001** [comment] 2020-09-07 15:40
I connect every time to Opensutitles.org (disconnect, restart PCT, connect) with my VPN on. 
No errors in console

**Comment by natbusa** [comment] 2020-09-08 04:43
As @pcenta has pointed out this issue is not easy to reproduce because depends on the ip address of vpn being blacklisted or not. About console errors you will probably will not find any because they are already caught in `src/app/lib/views/settings_container.js`

**Comment by kiriles90** [comment] 2020-09-26 01:24
@Persei08 close this since its not an issue with Popcorn Time?

**Closed as completed** 2020-09-26 14:16 UTC
