### ISSUE TITLE
Unable to close the application

### ISSUE THREAD

**Issue by SavySB** [popcorntime/popcorntime#1490] opened 2020-05-28 14:32 UTC
Operating System Version:

Windows 10 v1909

Popcorn Time Version:

0.4.4.0
Download date:

Updated on 28.05.2020
Download url (optional):

https://get.popcorntime.app/build/Popcorn-Time-0.4.4-win32-Setup.exe
#### Expected Behaviour

When pressing the close button? I don't know, maybe CLOSE?

#### Actual Behaviour

Nothing. Well, everything BUT close.

#### Steps to reproduce the behaviour

1. Open Application
2. Close it
3. Watch it not closing!

**Comment by Persei08** [comment] 2020-05-29 00:43
Duplicate of #1280 , it's a pinned one. No need to open new issues for already reported bugs. Thx

**Closed as completed by Persei08** 2020-05-29 00:43 UTC
