### ISSUE TITLE
Popcorn doesn't load and issues with your VPN 

### ISSUE THREAD

**Issue by alb277** [popcorntime/popcorntime#1523] opened 2020-06-12 20:39 UTC
Operating System Version:
 MAX Catalina 10.15.5

Popcorn Time Version:
 version 0.4.4 (0.4.4)

Download date:
 many years ago

Download url (optional):
 

#### Expected Behaviour
  load and watch
...  

#### Actual Behaviour
  stays loading and nothing appears, and if loads the title, it doesnt connect to your VPN (despite I purchased it)
...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment] 2020-06-12 20:58
looks like a duplicate of #1519

**Comment by dabs40** [comment] 2020-06-13 15:04
Hi all.
I have nvidia shield and not able to install popcorn time on it as it says this version is not compatible with this device yet ( for ANY version...tried them all).

nvidia shield pro 16gb,version 9. android security patch level 05/12/2019, build ppr1.180610.011.4199437_1915.8582, shield android tv sw version 8.1.1( 32.7.301.99).
To be honest, I managed to install it once or twice and every time it comes up with an error message ( something went wrong) and I only get the categories and the settings but no films/tv series are loading. 
Any thoughts?
Any help would be appreciated.thanks.
p.s: not using vpn.
app works on my pc,on my phone and even on my other android box (t95 max).

**Comment by dutchy1001** [comment] 2020-06-13 15:32
@dabs40 
I presume your trying to install this on a android tv, might be useful to give make and model.

PS:
Hyjacking a post with a different issue is normally not the way to go, create your own and fill in the template to give the devs a good idea what their dealing with or how to solve it.

**Comment by dabs40** [comment] 2020-06-13 17:13
> @dabs40
> I presume your trying to install this on a android tv, might be useful to give make and model.
> 
> PS:
> Hyjacking a post with a different issue is normally not the way to go, create your own and fill in the template to give the devs a good idea what their dealing with or how to solve it.

Hi dutchy1001.
I did say it was nvidia shield pro, as described in my previous post..;-)
sorry for "hijacking" thread but I thought it was a thread for problems with popcorn time...
first time on here apologies.
Also just realised I posted in an other thread which I think is the correct one...Popcorn time issue #679

**Comment by dutchy1001** [comment] 2020-06-13 19:19
@dabs40 

I had to google the "nvidia shield pro" I thought it was something to do with graphics card or software, sorry about that mistake. 
As far I can see this device is not running ARM (v7a) or a (x86) processor but a Tegra X1, this might be why it wont install or work properly.

EDIT:
issue 679 is not were you posted something and is closed 2 years ago.
EDIT2:
your t95max is running on an ARM processor, this is why it works on that device.

**Comment by dabs40** [comment] 2020-06-13 22:22
Hi dutchy1001.
thanks for the reply. I figured there was something wrong, yes, but people report different problems with the shield. Some manage to get it to work, watch movies, but struggle to shut it down. for some others, the app just crashes. it's just that it's not the same problem across the board, so I was wondering if anyone knew why and what needed to get done to get it to work...just threw it out there to fish...
Thanks for getting back to me though.
David.
________________________________

**Comment by kiriles90** [comment] 2020-09-26 01:19
@Persei08 close please

**Closed as completed** 2020-09-26 14:32 UTC
