### ISSUE TITLE
Subtitle does not work on Samsung DLNA

### ISSUE THREAD

**Issue by strinpe** [popcorntime/popcorntime#415] opened 2016-12-24 17:22 UTC
Operating System Version:
MacOS Sierra, latest version.

Popcorn Time Version:
Build #240, latest build.

Download date:
Yesterday.

#### Expected Behaviour
I expected to see the subtitle on DLNA Samsung.
...

#### Actual Behaviour
There is no subtitle, though it works fine in the Butter.

#### Steps to reproduce the behaviour
Choose a subtitle in the settings. And then stream it through DLNA. 

###
I Think the best way to fix this is to enable hardcoded subtitles. It would be great if you could choose hardcoded subtitles in the Settings menu.

Lovely x-mas

**Comment by ChrisAlderson** [comment] 2016-12-24 19:23
Dupe of #158

**Closed as completed by ChrisAlderson** 2016-12-24 19:23 UTC
