### ISSUE TITLE
any chance making a flatpak or appimage package for convenience to the end user?

### ISSUE THREAD

**Issue by pickybl2020** [popcorntime/popcorntime#1978] opened 2021-01-09 00:04 UTC
having popcorntime on a universal kind of package like flatpak or appimage 
that can run without root 

-saves from all the trouble install any extra dependencies or steps to configure it 
-will save the developers of the project a lot of time hunting down bugs
             - how about a "send feedback or bug report" feature/section built into the app where the end-user can send a report 
               directly from there to GitHub (given that the user will authorize/login through the app)?
-the end-user feels safer and way more comfortable to use 
             - saves from all the trouble install any extra dependencies or steps to configure it
             - it's all inside the package

**Comment by kiriles90** [comment] 2021-01-09 00:24
@pickybl2020 There is already an open issue/request about this. 
Closing because duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1006

**Closed as completed by kiriles90** 2021-01-09 00:24 UTC

**Comment by faveoled** [comment] 2024-02-19 09:09
what was your verdict?

**Comment by faveoled** [comment] 2024-02-19 13:20
it wasn't apparent if you accept such a proposition altogether. Plus the issue should still be open actually

**Comment by faveoled** [comment] 2024-02-19 13:35
I might want to do that, but #2889 needs to be solved first

**Comment by faveoled** [comment] 2024-02-19 13:39
> Just install it from the ready installers or get github actions to build your fork if its about that? (not saying #2889 isn't an issue, I left it open.., just saying its a separate issue..)

Flatpak uses their own build system. Plus aarch64 support needed in the best-case scenario

**Comment by faveoled** [comment] 2024-02-19 13:42
> Hmm I see but about aarch64 is that even available for NW.js for Linux?

Not sure. I've only found some third-party support

**Comment by faveoled** [comment] 2024-02-19 13:48
ok I'll just repackage existing deb then
