### ISSUE TITLE
Cant close application

### ISSUE THREAD

**Issue by Sheerabth** [popcorntime/popcorntime#1511] opened 2020-06-06 07:14 UTC
Operating System Version:

Windows 10

Popcorn Time Version:

v 0.4.4

Download date:

04-June-2020

Download url (optional):

https://get.popcorntime.app/build/Popcorn-Time-0.4.4-win32-Setup.exe

#### Expected Behaviour

Application should close when its intended to

#### Actual Behaviour

Application cannot be closed. Only possible way to close it for now is to end the task in task manager

#### Steps to reproduce the behaviour

1. Open the application
2. Run it for some time
3. Try closing it, and it won't

#### Screenshot of error from developer console (optional)

![Capture](https://user-images.githubusercontent.com/53862179/83938587-471a0300-a7f3-11ea-9c40-fca6a872a461.PNG)

**Comment by dutchy1001** [comment] 2020-06-06 10:36
read the pinned post on top first before maken a new post....

duplicate of #1280

**Comment by kiriles90** [comment] 2020-09-26 01:27
@Persei08 issue is fixed, close please

**Closed as completed** 2020-09-26 14:32 UTC
