### ISSUE TITLE
Missing download speed throttle like any other bittorrent client includes

### ISSUE THREAD

**Issue by notmutiny** [popcorntime/popcorntime#783] opened 2018-05-12 21:42 UTC
Operating System Version:
All

Popcorn Time Version:
All

Download date:
n/a

#### Expected Behaviour
Download speed -> limit -> e.g. 500kbps

#### Actual Behaviour
Start torrent -> popcorntime takes over my bandwidth -> rest of network cannot use internet because popcorntime is downloading at maximum capacity

#### Steps to reproduce the behaviour
1. use popcorntime
2. start streaming

**Comment by Persei08** [comment] 2018-05-13 10:08
Duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/400

**Closed as completed** 2018-05-13 10:11 UTC
