### ISSUE TITLE
can't close the program with the X mark and no subtitles

### ISSUE THREAD

**Issue by kenan94** [popcorntime/popcorntime#1291] opened 2020-04-09 13:22 UTC
Operating System Version:
 windows 7

Popcorn Time Version:
0.4.3.0

Download date:
08-04-2020

#### Expected Behaviour
close the window and no subtitles at all 
...

#### Actual Behaviour
the x didn't do nothing and i have to close it by ending the process from my task manager on widows 7
...

#### Steps to reproduce the behaviour

1. ... Click the x 
2. ...nothing happen
3. ...done !

**Comment by sheepdestroyer** [comment] 2020-04-09 15:14
0.4.3  windows 10 : can't close

**Comment by fehnicchio** [comment] 2020-04-09 15:37
me too

**Comment by dutchy1001** [comment] 2020-04-09 17:02
Why can't ppl read the existing issue's?? this is already been posted ( #1280 #1284 #1282 )and making new posts for this WILL NOT fix things quicker. Instead add to the existing post.

A temp fix is to untick "Clear Tmp Folder after closing app?" in the settings. The disadvantice of this is that you need to delete all movies/shows you watch manual from the "Cache Directory" location

**Comment by jordirar** [comment] 2020-04-09 17:07
When I choose to delete temporary subtitle files. It does not work. (in the advanced options)

Clean cache subtitles

**Comment by dutchy1001** [comment] 2020-04-09 18:33
@jordirar 
I never used the "Clean cache subtitles" as I don't think I need that. I manual delete the movies/shows anyway (which also then avoid the "not closing" issue").
Unfortunately Opensubtitle.org requires that ppl make an account now , following this you need to add the login details from opensubtitle.org into your popcorn settings to get subtitles. 
After you add your details the button to add a subtitle can be tricky and might need to be clicked a few times. This is only for the "movie" section as the "shows/series" will automatic add the language sub you set in the settings.
Your best is a clean install from build 407

**Comment by jordirar** [comment] 2020-04-12 00:45
> 
> 
> @jordirar
> I never used the "Clean cache subtitles" as I don't think I need that. I manual delete the movies/shows anyway (which also then avoid the "not closing" issue").
> Unfortunately Opensubtitle.org requires that ppl make an account now , following this you need to add the login details from opensubtitle.org into your popcorn settings to get subtitles.
> After you add your details the button to add a subtitle can be tricky and might need to be clicked a few times. This is only for the "movie" section as the "shows/series" will automatic add the language sub you set in the settings.
> Your best is a clean install from build 407

Ok.
First, perform the update. But, it is like an installation over the existing version.
then, delete the installed version and make it clean again. The problem persists.

What you mean is, do I have to create a new account? where? what is the section for Opensubtitle

**Comment by dutchy1001** [comment] 2020-04-12 09:59
If you haven't already have one you have to create an account at [opensubtitles.org](https://www.opensubtitles.org/en/search/subs), then fill your login details in to the settings from PCT. this has ben mentioned in many posts before.

**Comment by jordirar** [comment] 2020-04-12 20:01
> 
> 
> If you haven't already have one you have to create an account at [opensubtitles.org](https://www.opensubtitles.org/en/search/subs), then fill your login details in to the settings from PCT. this has ben mentioned in many posts before.

Ok. Thank you.

PCT does not use YIFY Subtitles? Only opensubtitles for create an account.

Another thing, I have been noticing that it takes PCT to start. With previous versions it happened to me. When I double click on the shortcut it takes a few seconds. I have an AMD A6 processor and 8 GB of ram, it shouldn't happen.

I have done a clean install, it keeps happening

**Comment by Persei08** [comment] 2020-04-12 23:01
Duplicate of #1280

**Closed as completed by Persei08** 2020-04-12 23:01 UTC
