### ISSUE TITLE
LG WebOS is not detected over DLNA

### ISSUE THREAD

**Issue by liorbp** [popcorntime/popcorntime#413] opened 2016-12-24 12:24 UTC
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10-0 (HEAD 28112f67)

Download date:
24/12/2016

#### Expected Behavior
LG WebOS should be detected as DLNA device so I can stream movies to it directly.

#### Actual Behavior
LG WebOS is not detected at all over DLNA.
This was already fixed in popcorntime.io project and is now broken again.

#### Steps to reproduce the behavior
Nothing special. See screenshot
![screenshot](https://cloud.githubusercontent.com/assets/7249539/21466967/308ba9ea-c9e4-11e6-8f7c-1a22ade0863b.png)

[hecfofbbdfadifpemejbbdcjmfmboohj-1482582166552.log.txt](https://github.com/popcorn-official/popcorn-desktop/files/671756/hecfofbbdfadifpemejbbdcjmfmboohj-1482582166552.log.txt)

**Comment by liorbp** [comment] 2016-12-24 12:31
Same error on the latest Jenkins build #240 (https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/240/)

I just installed v.0.3.8-5 master (7a424786) with a previous installer I had, and it detected my TV just fine (though the project is dead)
![image](https://cloud.githubusercontent.com/assets/7249539/21467015/b6066ffe-c9e6-11e6-80c9-f2b80b873158.png)

**Comment by ChrisAlderson** [comment] 2016-12-24 19:20
Dupe of #300

**Closed as completed by ChrisAlderson** 2016-12-24 19:20 UTC
