### ISSUE TITLE
Torrent downloading but playback freezes after some time

### ISSUE THREAD

**Issue by j-a-h-i-r** [popcorntime/popcorntime#1364] opened 2020-04-18 14:02 UTC
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4

Download date:

#### Expected Behaviour

File plays without interruption

#### Actual Behaviour

Playback starts normally but freezes after some random amount of time. Happens with MPC-HC. I've also tried with VLC, same behaviour.

**Comment by Persei08** [comment] 2020-04-18 21:56
What is the health of the torrent ?
else, which movie/episode, which quality ?

**Comment by j-a-h-i-r** [comment] 2020-04-19 02:58
Big bang theory. Tried several episodes of season 2/3. Health shows green
circle

**Comment by ar0ra1** [comment] 2020-04-20 16:24
I reported the same issue but on Mac, check your CPU usage.

**Comment by Persei08** [comment] 2020-04-20 19:58
Duplicate of #1350 #1373

**Closed as completed by Persei08** 2020-04-20 19:58 UTC
