### ISSUE TITLE
When installing new version, removes all settings and driectories

### ISSUE THREAD

**Issue by zephuros-droid** [popcorntime/popcorntime#1357] opened 2020-04-17 11:52 UTC
Operating System Version:
Windows 10

Popcorn Time Version:
0.440

Download date:
15/04/20

#### Expected Behaviour
Install and update, while keeping settings, watched history and favorites.
...

#### Actual Behaviour
Removed everything without asking and installed with defaults
...

#### Steps to reproduce the behaviour
Have a version installed and install this version!

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment] 2020-10-02 14:01
@Persei08 duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1579 (I know this issue was first but the other one has more info)

**Closed as completed** 2020-10-08 09:01 UTC
