### ISSUE TITLE
Popcorn keeps on loading. Yesterday it was working fine.

### ISSUE THREAD

**Issue by GNSubrahmanyam** [popcorntime/popcorntime#1329] opened 2020-04-14 16:35 UTC
![image](https://user-images.githubusercontent.com/18217008/79250245-00b3c200-7e9c-11ea-8d57-16934721a8c1.png)

Operating System Version:

Ubuntu 19.04

Popcorn Time Version:

0.3.10
Download date:

an year back
#### Expected Behaviour

App should load

#### Actual Behaviour

Keeps on loading

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment] 2020-04-14 17:27
Please read #1321 and #1323 and close this post.

**Comment by djashah** [comment] 2020-04-14 18:00
operating system 10.13.6

Popcorn time 4.3 was working all fine till last night i even download few movies. Today when i wanted to watch it does not show me any movies or shows.

**Comment by hafaber** [comment] 2020-04-14 18:33
I'm having the same issue: Always have been enyoing version 0.3.10 until today. Nothing loads. I hated the 0.4.3 version and i cannot use 0.4.4 because i am running on 32-bit.

**Comment by dutchy1001** [comment] 2020-04-14 18:41
@hafaber 
 version 0.4.4 has also a 32 bit setup or update file so that should not be a problem.
there is a newer [build 410](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/410/) you could try

**Comment by djashah** [comment] 2020-04-14 18:46
Hi, Thanks for the quick response ... i may sound nerd ... do i have to re install the zip link from the build 410 or the update zip file. i'll appreciate if you could guide me to do so. What would be the reason this happened coz last night i downloaded couple of movies ?? are there any limitations and restrictions.

thx

**Comment by dutchy1001** [comment] 2020-04-14 19:10
If you choose the one with "setup" in the file name then it would reinstall PCT and probably reset your "watched/favorite" settings. 
If you use the other one (without "setup" in the file name) you need to copy/paste these files into were you have pct installed (AppData\local\Popcorn-Time) and replace the excisting files. This will keep your "watched/favorite" settings.

Hope this makes any sence....

**Comment by esnover70** [comment] 2020-04-14 23:20
I have the same problem in windows

**Comment by djashah** [comment] 2020-04-15 10:21
> If you choose the one with "setup" in the file name then it would reinstall PCT and probably reset your "watched/favorite" settings.
> If you use the other one (without "setup" in the file name) you need to copy/paste these files into were you have pct installed (AppData\local\Popcorn-Time) and replace the excisting files. This will keep your "watched/favorite" settings.
> 
> Hope this makes any sence....

HI, Thanks I'm sorted.

**Comment by Persei08** [comment] 2020-04-15 13:18
Duplicate of #1321

**Closed as completed by Persei08** 2020-04-15 13:18 UTC

**Comment by hafaber** [comment] 2020-04-15 17:50
> @dutchy1001
> version 0.4.4 has also a 32 bit setup or update file so that should not be a problem.
> there is a newer build 410 you could try

I downloaded it, worked. but now the subtitling does not work

**Comment by team-pct** [comment] 2020-04-15 17:53
just give us time we are talking with opensubtitles about that

**Comment by hafaber** [comment] 2020-04-15 17:56
I am not talking just about opensubtitles. custom subtitles don't work either
