### ISSUE TITLE
Korean subtitles not displayed correctly

### ISSUE THREAD

**Issue by cozyplanes** [popcorntime/popcorntime#1524] opened 2020-06-13 15:16 UTC
Operating System Version:

win10
Popcorn Time Version:

0.4.4-0
Download date:

2020.06.13
Download url (optional):

popcorntime.app
#### Expected Behaviour

disaplys korean subtitles properly
korean looks like this: 한국어는 이렇게 생겼습니다.
#### Actual Behaviour

displays non korean strange words 

#### Steps to reproduce the behaviour

tested in interstellar movie
enable korean subtitle
only the first korean subtitle of the movie is displayed somewhat properly. (even this one, the end part isn't displayed correctly.
for example, if the subtitle should be displayed as
이렇게 자막이 표시됩니다.
it displays as 
이렇게 자막이 표시됩

#### Screenshot of error from developer console (optional)

not possible

========
just some words to add
korean is 2 bit language if i know correctly, so that may be the reason why it is being strange
also, when korean is encoded in ANSI format, it gets strange. it should be encoded in Unicode

**Comment by dutchy1001** [comment] 2020-06-15 17:59
Does this happen with the build in player?
If not, have you tried an external player like [SMplayer](https://www.smplayer.info/) or [VLC](https://www.videolan.org/index.ko.html)
These options will be available after you install either (or both) player(s) at the "watch now" button.

**Comment by kiriles90** [comment] 2020-10-30 22:03
Cannot reproduce, Korean display as expected here, including the specific words in the example.
Closing this but if the OP or someone else can provide more details so we can identify an issue if it actually exists I'll reopen.

**Closed as completed by kiriles90** 2020-10-30 22:03 UTC
