### ISSUE TITLE
Favorites - Limited Number

### ISSUE THREAD

**Issue by gericb** [popcorntime/popcorntime#1727] opened 2020-10-06 23:42 UTC
macOS 10.15.7
Popcorn: 0.4.4-0
Installed:  6-20-2020

Can only save 6 FAVORITES.  Despite being able to select several SERIES, and click the heart to add to bookmarks, when actually clicking the ❤️ for favorites, or the favorites category, it only is showing 6, though I should have 8 or 9 total.

Thank You,
Greg

**Comment by kiriles90** [comment] 2020-10-07 00:54
You are not limited to 6 favorites.. Something is bugged in your installation. Clean install the latest dev build from ci.popcorntime.app (438 at the moment) and please close this issue.

**Comment by Persei08** [comment] 2020-10-08 08:59
Can't reproduce

**Closed as completed by Persei08** 2020-10-08 08:59 UTC
