### ISSUE TITLE
Terms of Service Issue

### ISSUE THREAD

**Issue by Alex1087** [popcorntime/popcorntime#1720] opened 2020-10-03 10:11 UTC
When Terms of Service showing and click accept the movies is not showing only loading screen. I have to reopen the app to work properly.

**Comment by dutchy1001** [comment] 2020-10-03 10:26
All info asked on the template is there for a reason, without that info we can't offer any support.

**Comment by kiriles90** [comment] 2020-10-03 15:53
What @dutchy1001 said though this issue exists (probably duplicate of closed https://github.com/popcorn-official/popcorn-desktop/issues/880). It basically shows the first run disclaimer again randomly 1 in like 30-40 times and PCT wont load anything even if you click accept. You just have to close Popcorn Time and restart it again and everything works normally no settings or databases altered.
Attaching some screenshots below from when the error happens vs a normal run.

Normal run
![noerror](https://user-images.githubusercontent.com/38388670/94995783-3ca52580-05a9-11eb-847b-8c32dd777235.PNG)
Error run
![error](https://user-images.githubusercontent.com/38388670/94995787-4038ac80-05a9-11eb-91c9-ebf5575857f3.PNG)

**Comment by HaOz0r** [comment] 2020-10-21 15:59
When I'm receiving the ToS screen again, all my settings are getting reset to default. Any fix for this ? Thanks !

**Comment by kiriles90** [comment] 2020-10-21 16:07
They dont get reset. Its an error with Popcorn Time reading its database. Just exit and start it again. Your settings will be there.

**Comment by HaOz0r** [comment] 2020-10-21 16:11
> 
> 
> @HaOz0r They dont get reset. Its an error with Popcorn Time reading its database. Just exit and start it again. Your settings will be there.

@kiriles90 whenever i tried to do so, all the settings were reset and the folder itself got deleted and moved to the C:/ partition :( 
Will try again next time i get the ToS screen though, hope something changes :)

**Comment by kiriles90** [comment] 2021-01-05 04:21
@pcenta does https://github.com/pcenta/popcorn-desktop/commit/efa418bd9b25d91d0dd21e33e7e2f79f14957ae7 work? Why didnt you PR?
It happens too sporadically here to test it with any accuracy.

**Comment by pcenta** [comment] 2021-01-05 16:25
> @pcenta does https://github.com/pcenta/popcorn-desktop/commit/efa418bd9b25d91d0dd21e33e7e2f79f14957ae7 work? Why didnt you PR?
> It happens too sporadically here to test it reliably.

It doesn't work. I thought it fixed the problem but it didn't.

**Comment by kiriles90** [comment] 2021-01-05 16:33
I see, it does seem to help here but like I said I have this happen like 1 in 40 so I cant really know with any certainty if the 70-80 streak was a coincidence.

**Comment by kiriles90** [comment] 2021-01-06 02:39
@pcenta Hmm I think I found the issue, everytime this error occurs it seems its because `/src/app/lib/providers/tvshowtime.js` tries to load before `/src/app/lib/providers/cache_providerv2.js` has finished loading and https://github.com/popcorn-official/popcorn-desktop/blob/f14455085ad63b0bc4bc4747a263e1d2341ecdbf/src/app/lib/providers/tvshowtime.js#L14 returns with an error which bugs the app (`/src/app/bootstrap.js` does the loading)

Not 100% sure what to do about it though..

**Comment by pcenta** [comment] 2021-01-06 09:24
@kiriles90 
It's a bit annoying workaround that could cause issues going forward (hardcoded filenames and DOM queries). But at the same time I'm not familiar enough with everything to offer anything better.
My blind answer is what about if we expose 'initialized' boolean in providers and then in critical function check if all required modules are initialized.

**Comment by kiriles90** [comment] 2021-01-06 15:53
> hardcoded filenames and DOM queries  

Hmm the rest was there, I just added `tvshowtime.js`. Exposing an 'initialized' boolean isnt a bad idea but I think we'd still have to split the ones that need delaying from the ones that are needed for them or else we'll be relying on alphabetic sorting, which atm works for our purpose (IF we wait for 'initialized' before we jump to next) since tvshowtime is after cache on the alphabet, but doesnt mean will work in the future. Anyway I'll try to code and test the idea.
Just my concern is we dont add to the already bit long startup time. https://github.com/kiriles90/popcorn-desktop/commit/abfa4486c7652c67ca372d9c9cf3270693bc917d seems to be fine in that aspect but I'll think about it a bit more today/tomorrow before merging anything because its not the prettiest solution. Ofc if you want to add thoughts or code etc by all means. (and everyone else reading this)

**Comment by kiriles90** [comment] 2021-01-06 16:57
> hardcoded filenames and DOM queries  

GitHub's diff is a bit misleading, expand up/down the rest was there, I just added `tvshowtime.js`. Exposing an 'initialized' boolean isnt a bad idea but I think we'd still have to split the ones that need delaying from the ones that are needed for them or else we'll be relying on alphabetic sorting, which atm works for our purpose (IF we wait for 'initialized' before we jump to the next) since T(_vshowtime_) is after C(_ache_providerv2_) but doesn't mean will work in the future. Anyway I'll try to code/test the idea.

My concern is we don't add to the already bit long startup time. https://github.com/kiriles90/popcorn-desktop/commit/abfa4486c7652c67ca372d9c9cf3270693bc917d seems to be fine in that aspect effectively 0ms added, but I'll think about it a bit more today/tomorrow before merging anything because its not the prettiest solution code-wise.

Ofc if you want to add any thoughts or code etc by all means. (and anyone else reading this)

**Closed as completed** 2021-01-06 23:31 UTC
Labels: bug, help wanted
