### ISSUE TITLE
help please popcorn time stuck on loading 

### ISSUE THREAD

**Issue by orantd** [popcorntime/popcorntime#1361] opened 2020-04-17 22:44 UTC
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by orantd** [comment] 2020-04-17 22:51
Operating System Version: windows 10
Popcorn Time Version: Popcorn-Time 0.3.10
Download date: 18.04.2020

**Comment by outliners** [comment] 2020-04-18 07:55
same here.

**Comment by dutchy1001** [comment] 2020-04-18 08:11
please read through the issue's as this has been posted and fixed

Duplicate of #1321 #1346

**Comment by Persei08** [comment] 2020-04-18 13:53
Duplicate of #1321

**Closed as completed by Persei08** 2020-04-18 13:53 UTC

**Comment by orantd** [comment] 2020-04-18 14:09
> fixed
 Thanks
It worked out for me

I changed dns address
8.8.8.8
1.0.0.1
