### ISSUE TITLE
Add foreign movies section

### ISSUE THREAD

**Issue by GKid94** [popcorntime/popcorntime#1154] opened 2020-03-15 08:14 UTC
Add a section in Popcorn Time that has foreign movies, for example European, Asian and so on

**Comment by ivan1986** [comment] 2020-03-15 11:36
it's server issue, not client
api has films from other countries, but not so big
films gets from providers and you need add other provider from other films

just add some providers for other trackers
you can use my fork - https://github.com/popcorn-time-ru/popcorn-ru
it grab russian translated films from russain trackers, but it's us and european films translated to russian - i add filter for russian and indian films in spider, because most of it's is peace of shit.
it's easy to extend for any other providers

**Comment by GKid94** [comment] 2020-03-15 11:40
Can they add foreign movies on their servers too, I mean there is a Japanese anime section

**Comment by ivan1986** [comment] 2020-03-15 12:01
sorry, but i don't know same as themovedb for anime and not write anime api, if you can help - welcome for PR

**Comment by GKid94** [comment] 2020-03-15 12:08
> sorry, but i don't know same as themovedb for anime and not write anime api, if you can help - welcome for PR

I'm not a developer

**Comment by Persei08** [comment] 2020-03-16 17:41
@GKid94 [is a troll/spammer/whinner](https://github.com/popcorn-official/popcorn-desktop/issues?q=is%3Aissue+author%3AGKid94+). He open useless duplicate issues just to harass developers. He don't even want to make effort to follow the issue template, which he couldn't have missed with his 39th issues.

Also i'm closing because duplicate of #1110

**Closed as completed by Persei08** 2020-03-16 17:41 UTC
