### ISSUE TITLE
Some bugs :))

### ISSUE THREAD

**Issue by Majesty-cmd** [popcorntime/popcorntime#1307] opened 2020-04-11 13:20 UTC
Operating System Version:
 Windows 10 Pro

Popcorn Time Version: 
0.4.3-0

Download date:
09 April 2020

#### Expected Behaviour
Upgrade from 0.3.10
...

#### Actual Behaviour
lot of bugs
...
Hey, someone saw the difference when use the volume with [Windows 10 Pro my laptop] it appear like [ chrome-extension://... ] and now with my soundbar remote control i can just play and pause no more jump 10sec both ways. And yes the same issues like others no more subs or close from X just if i open for a couple of times the app and than maybe it works.
ThnkU

![capture_001_11042020_134824](https://user-images.githubusercontent.com/63502767/79044773-0a6cc980-7bff-11ea-881d-88d05494fe10.jpg)

**Comment by Persei08** [comment] 2020-04-12 22:53
Duplicate of #1294

**Closed as completed by Persei08** 2020-04-12 22:53 UTC
