### ISSUE TITLE
Getting rid of windows media control

### ISSUE THREAD

**Issue by pilsnerbeer** [popcorntime/popcorntime#1528] opened 2020-06-19 18:53 UTC
Operating System Version:
w10
Popcorn Time Version:

0.4.4

#### Steps to reproduce the behaviour

1. play a movie
2. adjust volume 

#### Screenshot of error from developer console (optional)

I dont know what exactly it says (starts with chrome://extension..) but it's visible when playing video through the default player, otherwise it's not there. 
![Screenshot_1](https://user-images.githubusercontent.com/36133540/85171082-9f7ae700-b26e-11ea-8b9d-d3dfc67bab1e.png)

**Comment by dutchy1001** [comment] 2020-06-20 12:12
This is already on the "bug" list.
Duplicate of #1294

**Closed as completed** 2020-06-20 13:05 UTC

**Comment by dutchy1001** [comment] 2020-07-11 21:11
There has been a "temp" fix posted in #1294 which I can confirm is working.
This will hopefully be implemented in the next dev build.
