### ISSUE TITLE
No TV Shows Subtitles (Only Movies)

### ISSUE THREAD

**Issue by gergesh** [popcorntime/popcorntime#111] opened 2016-03-18 13:59 UTC
Operating System Version:
Windows 10

Popcorn Time Version:
3.9

Download date:
Today (18/03)
#### Expected Behaviour

Fetch subtitles for TV shows
#### Actual Behaviour

Only fetch subtitles for movies
#### Steps to repoduce the behaviour

There are basically no subtitles available for TV shows.

**Comment by Breaking1** [comment] 2016-03-19 00:39
Have you tried setting a default subtitle in settings for tv shows?

You can't pick subtitles before starting an episode like on movies so you need to choose them after you start them in the internal player or set a default one in settings if you are using an external player.

**Comment by gergesh** [comment] 2016-03-19 03:17
The menu is empty. Even adding custom subs doesn't work, it just doesn't
display them. In VLC it does.

**Comment by Breaking1** [comment] 2016-03-19 05:15
Remember it can take a while for new episodes to get subtitles so be sure to check several episodes for subtitles.
And if you set a default subtitle in settings they will show when they are available in the selected language. It works perfect in my version. 

Can you take some screenshots and maybe edit your post so it includes the console log (f12 on windows) (cmd+0 Mac) and make sure to include any errors you find.

**Comment by gergesh** [comment] 2016-03-20 05:20
The subtitles are there in opensubtitles.org, just not in the program
itself.

**Comment by VitorVRS** [comment] 2016-03-24 22:24
I cant reproduce this, can you give some prints? Can you especify the steps to reproduce?

**Comment by jokhallouf** [comment] 2016-03-27 08:39
I have the same problem!
I have popcorntime.sh version 0.3.9-0
I have tried so many episodes of so many different series . all tell me no subtitles found! i have set a default subtitle in the settings as English . All movies work fine but series don't work. subtitles for series work in my popcorntime CE though for the same series !

**Comment by Breaking1** [comment] 2016-03-27 11:17
@jokhallouf   can you also try the latest build and see if the problem is fixed there?

https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/

If not can you take a screenshot of your console log when you start an episode you know have the correct subtitles but only get the msg "no subtitles found", make sure to include any errors that might be there.

You can get up the console log by pressing F12 in windows and cmd+0 on Mac OS.

It will hopefully help the dev's to see if there are anything they can do to fix this issue or if it's something else that needs correcting.

**Comment by jokhallouf** [comment] 2016-03-27 11:20
@Breaking1 i uninstalled all the popcorntime versions that i have and then installed popcorntime.sh only this time.
subtitles are working fine now with the TV shows.
i have a new problem now that i can no longer see the chromecast icon. that was never a problem with me before ! very weird subtitles fixed now no chromecast. uninstalled and installed the 0.3.9-0 version many times and restarted my PC still nothing.

**Comment by Breaking1** [comment] 2016-03-27 11:23
@jokhallouf  thank you so much for your quick reply, great that the subtitles thing is fixed in the latest build.

For the Chromecast issues, many has reported that reinstalling their Chromecast and Chromecast extension have fixed problems with Chromecast not showing up in PT.

Also if you have any special characters in the Chromecast name like an apostrophe or something remove it and then try.

**Comment by jokhallouf** [comment] 2016-03-27 11:25
@Breaking1 thanks for your continuous reply. i will try that and report back !

**Comment by jokhallouf** [comment] 2016-03-27 11:40
@Breaking1 did a factory reset on my chromecast. working perfectly fine now THANKS! :+1:

**Comment by Breaking1** [comment] 2016-03-27 11:44
@jokhallouf sweet, thanks for your feedback.

**Closed as completed** 2016-04-22 19:26 UTC
