### ISSUE TITLE
all the movies and series lost sub titles. When they will be fixed?

### ISSUE THREAD

**Issue by nunocatorze** [popcorntime/popcorntime#1269] opened 2020-04-06 16:37 UTC
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment] 2020-04-06 18:02
Please read through the issue list to find multiple issues about this. Keep making new posts doesnt help this.

**Comment by jurly5** [comment] 2020-04-07 01:34
Me too for 3 days. I tried to figure out but seem, I couldn't find how to figure out that subtitle return?

**Comment by kiriles90** [comment] 2020-04-07 06:50
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by Persei08** [comment] 2020-04-08 11:03
Duplicate of #1252

**Closed as completed by Persei08** 2020-04-08 11:03 UTC
