### ISSUE TITLE
Streaming No longer works due to newest version of upnp-mediarenderer-client.  Reverting to Old version from 3.8.0 works

### ISSUE THREAD

**Issue by Frankenmint** [popcorntime/popcorntime#138] opened 2016-04-11 04:13 UTC
**TO FIX** 
Edit 2:  /u/McShmoopy of Reddit [shared a link](https://www.reddit.com/r/PopCornTime/comments/4e2g95/are_there_any_other_resources_we_can_use_to_ask/) to another thread!  Pretty much:

> I had the same problem. After searching in the PT console and some experimenting i found the solution. The problem is caused by upnp-mediarenderer-client module. 
> You have to replace this folder in node_modules with an older version. I replaced it with the one from 0.3.8 and everything seems to work just fine.

Luckily I kept my old copy, the link to this file is here: `/Applications/Popcorn-Time.app/Contents/Resources/app.nw/node_modules`  

As the other thread said, just copy that file from your OLD copy of Popcorntime into your new folder and it works (no more preview screen on the computer but honestly I don't even care, this is awesome)!

**Comment by Breaking1** [comment] 2016-04-11 20:02
~~Can you please try the lastes build from here and confirm if the problem is fixed:~~

You can view the latest changes [here](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/changes).

https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/

**EDIT:**

Nevermind, someone already confirmed that the problem is fixed in the lastest build.

**Closed as completed** 2016-10-20 17:30 UTC
