### ISSUE TITLE
american horror story

### ISSUE THREAD

**Issue by patiartus** [popcorntime/popcorntime#1119] opened 2020-01-16 21:42 UTC
the first episode of the season one doesn't have any image, just the sound

**Comment by Persei08** [comment] 2020-01-17 08:56
codec issue.

as a workaround, Install VLC, restart PT so it detect VLC, and in the dropdown menu of the 'watch now' button choose to play with VLC

**Comment by Persei08** [comment] 2020-02-13 20:42
Duplicate of #1029

**Closed as completed by Persei08** 2020-02-13 20:42 UTC
