### ISSUE TITLE
Spinning circles of nothing

### ISSUE THREAD

**Issue by jimsuev** [popcorntime/popcorntime#1375] opened 2020-04-19 19:01 UTC
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.1

Download date:
4 Apr 2020
#### Expected Behaviour
<Open and show me available titles to watch.
...

#### Actual Behaviour
<Program opens and get to spinning circles and that's all it does.
![Annotation 2020-04-19 150116](https://user-images.githubusercontent.com/63857454/79697093-b1c8ac80-824e-11ea-85e1-1869c4cfe553.jpg)

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by gabrielmancini** [comment] 2020-04-19 19:04
+1

**Comment by KingOrdinaryCitizen** [comment] 2020-04-19 19:15
Duplicate of #1321 has to do with the changed API links.

Either update 4.4 or edit the source code manually to point to the new API.

**Comment by jimsuev** [comment] 2020-04-19 20:46
Downloaded the 

Popcorn-Time-0.4.3-win64-Setup.exe
--


and still get the same result. I have no idea how to edit the source code manually.

**Comment by Persei08** [comment] 2020-04-19 20:49
Please don't create duplicate issue. v4.3 is too old, the api domain was taken down and updated in v4.4

**Closed as completed by Persei08** 2020-04-19 20:49 UTC

**Comment by jimsuev** [comment] 2020-04-19 20:54
Where can I get v4.4 for download. I'm new to this type of forum.

**Comment by KingOrdinaryCitizen** [comment] 2020-04-19 22:07
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/
