### ISSUE TITLE
No video just audio 

### ISSUE THREAD

**Issue by carolaquintanilha** [popcorntime/popcorntime#1008] opened 2019-05-17 00:56 UTC
Operating System Version:

Popcorn Time Version:
 the latest

Download date:
 about a month ago 

I tried to watch Glee, but there's only audio and no video. It opens when i put MPV, but then, i can't watch because there's no subtitles for my language.

#### Steps to reproduce the behaviour

1. All episodes of "Glee"'s Seasons.

**Comment by kronikpillow** [comment] 2019-05-19 00:44
This issue is already opened at https://github.com/popcorn-official/popcorn-desktop/issues/1007

**Comment by Persei08** [comment] 2020-02-17 23:27
Duplicate of #1007

**Closed as completed by Persei08** 2020-02-17 23:27 UTC
