### ISSUE TITLE
Not working on fedora 28

### ISSUE THREAD

**Issue by ddipak** [popcorntime/popcorntime#822] opened 2018-07-26 12:51 UTC
Operating System Version:

Fedora 28
Popcorn Time Version:

3.10
Download date:

26 Jul 2018
#### Expected Behaviour

It crashes on start

[101684.560168] Popcorn-Time[25202]: segfault at 20 ip 00007f1a4412a488 sp 00007ffd7bf30e50 error 4 in libnode.so[7f1a44000000+472000]
[101685.096172] traps: Popcorn-Time[25151] trap invalid opcode ip:7f672f95276e sp:7ffdd45ea350 error:0 in libnw.so[7f672db32000+5b7b000]

**Comment by Persei08** [comment] 2018-07-27 08:21
Duplicate of #776

**Closed as completed** 2018-11-24 21:03 UTC
