### ISSUE TITLE
Latest 374 build not opening

### ISSUE THREAD

**Issue by YechiamW3** [popcorntime/popcorntime#1109] opened 2019-12-21 19:14 UTC
Operating System Version:
Windows 10 64 bit

Popcorn Time Version:
3.10 build 374

Download date:
21/12/19

#### Actual Behaviour
App won't open

#### Steps to reproduce the behaviour
Simply try to open the latest build

-----

Hi,
so after using the standard official build (I believe it's 200) and having trouble syncing with trakt.tv, I decided to try the latest dev build which I've obtain [here](https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastBuild/). After downloading it with the .exe file and the .zip file (64bit), both versions did not open up. I've confirmed that it's an issue specifically with that version by downloading a different one (363) which worked (almost) perfectly fine - at least it opened up, but it had different issues like weirdly big minimize-maximize-exist buttons and not having favorites.

Can anyone confirm this? Or is it an issue on my end?

**Comment by reddo** [comment] 2019-12-21 19:41
I confirm, the same happened to me.

**Comment by Franchute13** [comment] 2019-12-22 20:20
same #1107
Try 32bit version!
Chromecast doesn't work either

**Comment by Persei08** [comment] 2020-02-13 22:16
Duplicate of #1107

**Closed as completed by Persei08** 2020-02-13 22:16 UTC
