### ISSUE TITLE
Play next episode automatically does not work

### ISSUE THREAD

**Issue by Kanzy11** [popcorntime/popcorntime#1513] opened 2020-06-06 16:48 UTC
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment] 2020-06-07 19:16
duplicate of #1352

**Comment by kiriles90** [comment] 2020-09-26 20:29
@Persei08 duplicate of #1352, close this please

**Closed as completed** 2020-09-28 17:31 UTC
