### ISSUE TITLE
Subtitles not working.

### ISSUE THREAD

**Issue by Blasphemous87** [popcorntime/popcorntime#2779] opened 2023-10-21 23:58 UTC
PLEASE HELP ME.
My subtitles are not working at all 
If you are asking a question rather than filing a bug, try one of these instead:
- Wiki & FAQ (https://github.com/popcorn-official/popcorn-desktop/wiki)
- Reddit /r/PopCornTimeApp (https://www.reddit.com/r/PopCornTimeApp/)
- Popcorn Time Forum (https://discuss.popcorntime.app/)
-->

Operating System Version:
Windows 10 pro
Popcorn Time Version:

Download date:

Download url:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment] 2023-10-22 08:09
Not much info to go on here.
Just make sure you have an account with www.opensubtitles.org and have your credentials filled in in the settings.
Not every serie or movie has subs, but it's very rare there aren't any.
Open subs could have maintenance, might be 1 reason it won't work.
Make sure you are using latest (dev) build.

As this is not a bug but either internet or user error I will close this, feel free to answer here if you have more info

**Closed as completed by dutchy1001** 2023-10-22 08:09 UTC

**Comment by SebastianSava** [comment] 2023-10-22 14:11
Related with #2780
