### ISSUE TITLE
App crashing when trying to open on Mac

### ISSUE THREAD

**Issue by seran-shan** [popcorntime/popcorntime#2366] opened 2021-12-21 14:26 UTC
Operating System Version: macOS Monterey 12.0.1

Popcorn Time Version: 0.4.6

Download date: 20.12.21

Download url (optional): With brew

#### Expected Behaviour
Open as normal

#### Actual Behaviour
Crashing when opening

#### Steps to reproduce the behaviour

1. Try opening app on Mac

**Comment by kiriles90** [comment] 2021-12-21 19:01
Closing because duplicate of #2365 (and of many others). Also needs #2062 to be resolved like I mentioned in the rest.

**Closed as completed by kiriles90** 2021-12-21 19:01 UTC

**Comment by Kief5555** [comment] 2021-12-30 21:15
https://youtu.be/3IZid6lBMJM I have a fix, you can watch from the link.

**Comment by saintpepsicola** [comment] 2022-01-16 19:24
thanks @Kief5555 . This should be built in

**Comment by jlrodriguezdev** [comment] 2022-02-22 00:33
@Kief5555 Thanks you, Is working, good tutorial but need to delete old version from Applications folder 🙏🏽

**Comment by Kief5555** [comment] 2022-02-24 19:22
@saintpepsicola @jlrodriguezdev Your most welcome.

**Comment by icavot** [comment] 2022-04-06 14:39
I have similar problem from a few days
In my case I have the last update of Monterrey and v04.7. Popcorn-Time
¿Do you have any solution on this? ¿Can I test this solution for these versions?
Thanks!

**Comment by fulcus** [comment] 2022-12-07 15:31
@Kief5555 video has been removed

**Comment by Kief5555** [comment] 2022-12-07 15:32
> @Kief5555 video has been removed

Read the wiki then
