### ISSUE TITLE
Problem playing some episodes in the macbook app

### ISSUE THREAD

**Issue by EmileCouto** [popcorntime/popcorntime#1127] opened 2020-02-02 14:07 UTC
**Operating System Version:** 

Mac OS Catalina 10.15.2

**Popcorn Time Version:** 

Version 0.3.10 (0.3.10)

**Download date:** 

December 2019

#### Expected Behaviour: 

Play the TV shows normally.

...

#### Actual Behaviour

The App is not playing some TV shows or episodes

...

#### Steps to reproduce the behaviour

I just tried to play the TV shows normally.

Some TV shows are having problems. They don't load normally and there's always an error message saying that "the video cannot be loaded, either because of the server or the network connection failed or because the format is not supported". 

Can you help me with that?

Here are some of the series with problems:

Arrow: Season 8, Episode 9 and 10.
Supernatural: 15 season, episode 9, 10 and 11.
Agents of Shield: Season 6, all episodes
This is us: 4 season, episodes 10, 11 and 12.
Batwoman: 1 season, episodes 8 and 11.
Criminal Minds: 15 seasons, all episodes.
Supergirl: 5 seasons, episodes 10 and 11.

Ps: these problems occurred in the mackboor air application.

**Here is the screenshot:**
![image](https://user-images.githubusercontent.com/60572943/73609189-03e02700-45aa-11ea-87b5-e901eac4436d.png)

**Comment by Persei08** [comment] 2020-02-06 20:09
I'm on Ubuntu, I tried few ones of the named episodes but can't reproduce, everything works fine for me.

Here I've collected the format and codecs to see if it's related to codecs or not

 - Arrow S08E09
    - 480p : mkv-avc-aac (container-video-audio)
    - 720p : mkv-avc-eac3
 - Arrow S08E10
    - 480p : mkv-avc-aac
    - 720p : mkv-avc-eac3
 - Supernatural S15E09
    - 480p : mkv-avc-aac
    - 720p : mkv-avc-eac3
 - Supernatural S15E10
    - 480p : mkv-avc-eac3
    - 720p : mkv-avc-eac3
 - Supernatural S15E11
    - 480p : mkv-avc-aac
    - 720p : mkv-avc-eac3
 - Batwoman S01E08
    - 480p : mkv-avc-eac3
    - 720p : mkv-avc-eac3
 - Batwoman S01E11
    - 480p : mkv-avc-aac
    - 720p : mkv-avc-aac
---
 - Batwoman S01E09 (you don't named this one)
    - 480p : mkv-avc-aac
    - 720p : mkv-avc-eac3
 - Batwoman S01E10 (you don't named this one)
    - 480p : mkv-avc-aac
    - 720p : mkv-avc-eac3
---

So, I don't know if you tried 480p, 720p or both for each episodes.
You named Batwoman S01E08 & E11 so I guess you were able to watch E09 & E10. Am I wrong ?

Batwoman S01E08 is mkv-avc-eac3 and E11 is mkv-avc-aac, but at the same time if you were able to watch E09 & E10, so it look like it isn't codec related.

So I think maybe it's just a random bug, did you tried to restart PT when you get those messages ?

Eventually can you retry Batwoman S01E08 to E11 and confirm us if you still have the issues ?

Else a workaround could be to install VLC and choose to play in it, with the drop-down menu of the watch now button

**Comment by EmileCouto** [comment] 2020-02-06 20:49
Hi! I appreciate your reply.

Answering your questions: Yes, I tried to watch in 720p, as usual.

About the Batwoman episodes, yes I was able to watch episodes 09 and 10. The only ones that didn't work properly were episodes 08 and 11. And I still can't watch the episodes. The problem persists.

No, I didn't try to restart. How do I do that?

I'll try the VLC. If it works I'll come back here to let you know.

Thanks!

**Comment by Persei08** [comment] 2020-02-06 21:15
>No, I didn't try to restart. How do I do that?

By closing all PT windows and relaunching it :)

**Comment by EmileCouto** [comment] 2020-02-07 12:57
Oh, that? Yeah, I already tried restarting the PT. But it didn't work out.

**Comment by Persei08** [comment] 2020-02-10 23:22
Maybe, it's specific to osx version, maybe some codecs support less decoding profiles i don't really know.
I don't have a mac, so if someone else can tests those episodes above mentioned (at least in 720p) and confirm or not the same results, it will help.

@EmileCouto for the moment, you can play in an external player like VLC or Mplayer

**Comment by EmileCouto** [comment] 2020-02-11 00:08
@Persei08 Thanks for your help.

At the moment I am using VLC to watch the episodes and it is working perfectly ;)

**Comment by sohojmanush** [comment] 2020-02-13 14:12
Having the same issues as @EmileCouto on mac os x 10.14.6, anyone knows, how to generate a log for that?

**Comment by Persei08** [comment] 2020-02-13 15:41
Hi @sohojmanush,

You can open console window with F12 key then selecting console tab. You will find some logs here.

Else what you can do too, is analysing the video file causing this issue with mediainfo, and sharing those detail here (paste those details in a code block).

Also if you have time, can you please test Batwoman S01E08, S01E10, S01E11 in 720p and tell which one work and don't work for you?

Finally, as a workaround you can play with VLC or Mplayer.

**Comment by sohojmanush** [comment] 2020-02-14 03:02
`[INFO] Watching: Batwoman - Season 1, Episode 8 - A Mad Tea-Party
[ERROR] video.js error code: 4 vjs.MediaError {code: 4, message: "The video could not be loaded, either because the …rk failed or because the format is not supported."}
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported. vjs.MediaError {code: 4, message: "The video could not be loaded, either because the …rk failed or because the format is not supported."}
Uncaught (in promise) DOMException: Failed to load because no supported source was found.`

S01E10 working,

`INFO] Watching: Batwoman - Season 1, Episode 11 - An Un-Birthday Present
[ERROR] video.js error code: 4 vjs.MediaErrorcode: 4message: "The video could not be loaded, either because the server or network failed or because the format is not supported."__proto__: ObjectMEDIA_ERR_ABORTED: 1MEDIA_ERR_CUSTOM: 0MEDIA_ERR_DECODE: 3MEDIA_ERR_ENCRYPTED: 5MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4code: 0constructor: (code)MEDIA_ERR_ABORTED: 1MEDIA_ERR_CUSTOM: 0MEDIA_ERR_DECODE: 3MEDIA_ERR_ENCRYPTED: 5MEDIA_ERR_NETWORK: 2MEDIA_ERR_SRC_NOT_SUPPORTED: 4arguments: nullcaller: nulldefaultMessages: Object1: "You aborted the video playback"2: "A network error caused the video download to fail part-way."3: "The video playback was aborted due to a corruption problem or because the video used features your browser did not support."4: "The video could not be loaded, either because the server or network failed or because the format is not supported."5: "The video is encrypted and we do not have the keys to decrypt it."__proto__: Object__defineGetter__: __defineGetter__()arguments: nullcaller: nulllength: 2name: "__defineGetter__"__proto__: ()apply: apply()arguments: (...)get arguments: ThrowTypeError()arguments: (...)caller: (...)length: 0__proto__: ()apply: apply()arguments: (...)get arguments: ThrowTypeError()set arguments: ThrowTypeError()bind: bind()call: call()caller: (...)get caller: ThrowTypeError()set caller: ThrowTypeError()constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()__proto__: Object[[FunctionLocation]]: <unknown>set arguments: ThrowTypeError()bind: bind()call: call()caller: (...)get caller: ThrowTypeError()set caller: ThrowTypeError()constructor: Function()length: 0name: ""toString: toString()Symbol(Symbol.hasInstance): [Symbol.hasInstance]()__proto__: Object[[FunctionLocation]]: <unknown>__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: __proto__()errorTypes: Array[6]length: 1name: ""prototype: Object__proto__: ()[[FunctionLocation]]: video.dev.js:3448[[Scopes]]: Scopes[1]message: ""status: null__proto__: Object
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported. vjs.MediaError {code: 4, message: "The video could not be loaded, either because the …rk failed or because the format is not supported."}
Uncaught (in promise) DOMException: Failed to load because no supported source was found.
`
I will try to post as many console output as I can.

**Comment by sohojmanush** [comment] 2020-02-14 03:03
I will try to post as many console output as I can.

**Comment by Persei08** [comment] 2020-02-14 11:14
So, You have the same result as @EmileCouto.... seem specific to macOS and the bundled ffmpeg lib in the custom nwjs.

~~For the moment we know it affect some mkv-avc-eac3 and mkv-avc-aac files but not all.~~
My reports on format was messed up, my bad :/

#### Mediainfo results:

Batwoman S01E08 720p (NOK):

```
General
Unique ID                                : 309317426237721779690535522379668939532 (0xE8B45E8DCCE4A7FF518D4B3FAED8630C)
Complete name                            : /tmp/Butter/c78aa7199a3602caf7ad5b13553a31e7debb92c7/Batwoman.S01E08.A.Mad.Tea-Party.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb[eztv].mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 833 MiB
Duration                                 : 41 min 50 s
Overall bit rate                         : 2 782 kb/s
Encoded date                             : UTC 2019-12-02 10:18:27
Writing application                      : mkvmerge v23.0.0 ('The Bride Said No') 64-bit
Writing library                          : libebml v1.3.6 + libmatroska v1.4.9

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 41 min 50 s
Bit rate mode                            : Constant
Bit rate                                 : 2 140 kb/s
Nominal bit rate                         : 6 000 kb/s
Width                                    : 1 280 pixels
Height                                   : 640 pixels
Display aspect ratio                     : 2.000
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.109
Stream size                              : 641 MiB (77%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced Audio Coding 3
Codec ID                                 : A_EAC3
Duration                                 : 41 min 50 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 187.500 FPS (256 SPF)
Compression mode                         : Lossy
Stream size                              : 192 MiB (23%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 41 min 44 s
Bit rate                                 : 72 b/s
Count of elements                        : 743
Stream size                              : 22.0 KiB (0%)
Title                                    : SDH
Language                                 : English
Default                                  : No
Forced                                   : No
```
---
Batwoman S01E10 720p (OK):
```
General
Unique ID                                : 80584203651991289299845785655824202457 (0x3C9FF3FD6E4815A06612D91C6EF1BAD9)
Complete name                            : /tmp/Butter/8e8539593f50e630f1ca4cd60b2a3b553e4950b8/batwoman.s01e10.internal.720p.web.h264-trump[eztv].mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 17.5 MiB
Duration                                 : 42 min 11 s
Overall bit rate                         : 58.0 kb/s
Encoded date                             : UTC 2020-01-20 06:50:36
Writing application                      : mkvmerge v41.0.0 ('Smarra') 64-bit
Writing library                          : libebml v1.3.9 + libmatroska v1.5.2
IsTruncated                              : Yes

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Main@L3.1
Format settings                          : CABAC / 3 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 3 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 42 min 11 s
Bit rate mode                            : Constant
Nominal bit rate                         : 2 432 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.110
Language                                 : English
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : A_AAC-2
Duration                                 : 42 min 11 s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Title                                    : English
Language                                 : English
Default                                  : No
Forced                                   : No
```


---
Batwoman S01E11 720p (NOK):
```
General
Unique ID                                : 281229341439066112258659411013438461210 (0xD392CD0DCC1B46B8347089B163C2D51A)
Complete name                            : /tmp/Butter/423d5eecd9a0c52ca2de09567a01a14ff90f821f/Batwoman.S01E11.An.Un-Birthday.Present.720p.AMZN.WEB-DL.DDP5.1.H.264-NTb[eztv].mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 877 MiB
Duration                                 : 42 min 23 s
Overall bit rate                         : 2 894 kb/s
Encoded date                             : UTC 2020-01-27 09:06:58
Writing application                      : mkvmerge v23.0.0 ('The Bride Said No') 64-bit
Writing library                          : libebml v1.3.6 + libmatroska v1.4.9

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 42 min 23 s
Bit rate mode                            : Constant
Bit rate                                 : 2 252 kb/s
Nominal bit rate                         : 6 000 kb/s
Width                                    : 1 280 pixels
Height                                   : 640 pixels
Display aspect ratio                     : 2.000
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.115
Stream size                              : 683 MiB (78%)
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : E-AC-3
Format/Info                              : Enhanced Audio Coding 3
Codec ID                                 : A_EAC3
Duration                                 : 42 min 23 s
Bit rate mode                            : Constant
Bit rate                                 : 640 kb/s
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 187.500 FPS (256 SPF)
Compression mode                         : Lossy
Stream size                              : 194 MiB (22%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Duration                                 : 42 min 13 s
Bit rate                                 : 66 b/s
Count of elements                        : 710
Stream size                              : 20.7 KiB (0%)
Title                                    : SDH
Language                                 : English
Default                                  : No
Forced                                   : No
```

Thx @sohojmanush . you can format some block of text by adding it between 2 lines containing just ``` for better reading.

Also, I don't think console logs are really what we need here, because it will always end with `Failed to load because no supported source was found` since the video can't be played. Mediainfo details eventually will help to detect what kind of encoding aren't supported.

BTW thanks for your efforts.

**Comment by sohojmanush** [comment] 2020-02-14 23:20
Also, there is a startup issue on mac os x, fresh start of PT or any shows on Pt freezes the machine momentarily.

**Comment by Persei08** [comment] 2020-02-17 17:21
Oops, I accidentally closed the issue.

@sohojmanush, other issue = other report :) ... but I sound like you describe issue #962 for me

**Comment by team-pct** [comment] 2020-03-14 09:41
Fixed get the last build from ci.popcorntime.app

**Closed as completed by team-pct** 2020-03-14 09:41 UTC
