### ISSUE TITLE
popcorntime crashes on loading

### ISSUE THREAD

**Issue by Kidlike** [popcorntime/popcorntime#781] opened 2018-05-10 10:08 UTC
Operating System Version:
Fedora 27 - 4.16.6-202.fc27.x86_64

Popcorn Time Version:
0.3.10

Download date:
Today

#### Expected Behaviour
It should open...

#### Actual Behaviour
The loading bar appears for 1-2 seconds and then the app crashes.
Same after removing my ~/.config/Popcorn-Time/

#### Steps to reproduce the behaviour
./Popcorn-Time

**Comment by Kidlike** [comment] 2018-05-10 10:14
I didn't know how to upload the popcorn-time crash reports... if anyone has a better suggestion let me know.

https://www.justbeamit.com/zfzae

**Comment by EliaGeretto** [comment] 2018-05-10 12:00
This is likely to be related to #776 and #777, probably a duplicate of #776. A system update probably broke one of the dependencies.

**Comment by Kidlike** [comment] 2018-05-10 12:35
Seems like it yeah.

So we're stuck I guess huh...

**Comment by christian130** [comment] 2018-05-11 20:44
#774

**Comment by christian130** [comment] 2018-05-11 20:50
those #776 #777 and therefore #776 could be fixed with the proper npm and node version... actually is what @Persei08 appointed
```
user@host:~ $ node -v
v8.11.1
user@host:~ $ npm -v
4.6.1
```

**Comment by Persei08** [comment] 2018-05-11 21:33
NO !! This is not related ! 
It was only for #774 and maybe #777

**Comment by christian130** [comment] 2018-05-13 03:16
duplicate #776

**Comment by christian130** [comment] 2018-05-13 03:17
Duplicate of #776

**Closed as completed** 2018-05-13 10:12 UTC
