### ISSUE TITLE
Closedown in Windows 10 not working

### ISSUE THREAD

**Issue by geoffrey5239** [popcorntime/popcorntime#1851] opened 2020-11-20 10:32 UTC
On my Windows 10 computer I can only close Popcorn Time by going to Task Manager,  The X does nothing.

**Comment by dutchy1001** [comment] 2020-11-20 10:34
Again you didnt't fill the requested fields in the issue form, read the pinned topic on top

**Comment by kiriles90** [comment] 2020-11-20 11:23
Duplicate of #1280

**Closed as completed by kiriles90** 2020-11-20 11:23 UTC

**Comment by Persei08** [comment] 2020-11-20 13:45
This is already fixed in latest dev builds.
