### ISSUE TITLE
Not loading for a month now and its the new update of popcorntime on windows 10.

### ISSUE THREAD

**Issue by Nkbaby** [popcorntime/popcorntime#1412] opened 2020-04-26 23:31 UTC
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment] 2020-04-27 09:36
ever thought of reading through the issue's here and see for a solution?

Duplicate of #1361 #1363  #1393

**Comment by Persei08** [comment] 2020-04-27 13:48
Please follow guidelines and make a valid report if necessary.

**Closed as completed by Persei08** 2020-04-27 13:48 UTC
