### ISSUE TITLE
app won't close and X button won't work 

### ISSUE THREAD

**Issue by wintergotham** [popcorntime/popcorntime#1919] opened 2020-12-20 10:07 UTC
popcorn time won't close and when i press the - button or the reduce page one it works but not the X that allows to close the app. please fix it asap

**Comment by dutchy1001** [comment] 2020-12-20 11:12
please update to a dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**, if the issue still happens after this you can report back or close if fixed.

**Comment by Persei08** [comment] 2020-12-20 11:15
Hi, 

Your issue report don't follow the issue/bug template, is duplicate of #1280 "Popcorn time wont close", which is also pinned on the issue board. 
Please be aware of all this, we try to be organized enough for avoiding the issues board to become too messy and facilitating understanding and tracking of issues. I hope you can understand. :)


This issue is already fixed (at least partially, but it no longer block the exit of the app) in dev branch. , so you either wait for next release, or you use the latest dev build from https://ci.popcorntime.app/job/Popcorn-Time-Desktop/

Thx

**Closed as completed by Persei08** 2020-12-20 11:15 UTC
