### ISSUE TITLE
no movie listings for 2021

### ISSUE THREAD

**Issue by stsbware** [popcorntime/popcorntime#2038] opened 2021-02-25 23:39 UTC
Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment] 2021-02-26 00:06
Duplicate of pinned #1690. Closing.

**Closed as completed by kiriles90** 2021-02-26 00:06 UTC
