### ISSUE TITLE
Program can not be closed by the X

### ISSUE THREAD

**Issue by qdubz** [popcorntime/popcorntime#1857] opened 2020-11-25 03:46 UTC
Win10 X64
Dell XPS15

Program will not close when clicking X. I can only close it by going into task manager and ending the task.

**Comment by qdubz** [comment] 2020-11-25 03:48
0.4.4-0 "Love in the Time of Corona Beta
HEAD (b2007344)

**Comment by Persei08** [comment] 2020-11-25 07:33
Please follow guidelines and make a valid report.

Also it's duplicate of #1280

**Closed as completed by Persei08** 2020-11-25 07:33 UTC
