### ISSUE TITLE
Option to choose a custom subtitle for Chromecast

### ISSUE THREAD

**Issue by Dulb26** [popcorntime/popcorntime#942] opened 2019-01-03 16:14 UTC
Operating System Version:
Windows 10

Popcorn Time Version:
Popcorn-Time-0.3.9 - Build 116

Download date:
06/26/2016

Expected Behaviour
Let me choose a custom subtitle (.srt) when playing on Chromecast.

Actual Behaviour
I Can only choose custom subtitles when playing in Butter player or external players like VLC.

Steps to reproduce the behaviour
1.Open PopcornTime
2. Choose a Movie/Serie
3. Choose Chromecast
4. (Don't) Choose custom subtitles

**Comment by osrl** [comment] 2020-03-17 18:50
Or any dlna device

**Comment by kiriles90** [comment] 2020-09-26 16:09
@Persei08 duplicate of #1540 , close please

**Closed as completed** 2020-09-26 16:21 UTC
