### ISSUE TITLE
Progress bar and mouse pointer appear constantly

### ISSUE THREAD

**Issue by DejanPerovic** [popcorntime/popcorntime#1126] opened 2020-02-01 23:05 UTC
Operating System Version:
Windows 10

Popcorn Time Version:
0.3.10-0

Download date:
2019

#### Actual Behaviour
The progress bar and mouse pointer appear constantly sometimes on every few seconds.

**Comment by Persei08** [comment] 2020-02-06 20:13
Do you use a laser mouse ? if yes, does it still occur if you disable the mouse ?

**Comment by Persei08** [comment] 2020-02-13 20:17
Closing because duplicate of #992 or #900 .
Correct me if I'm wrong

**Closed as completed by Persei08** 2020-02-13 20:17 UTC

**Comment by DejanPerovic** [comment] 2020-02-28 17:57
> Do you use a laser mouse ? if yes, does it still occur if you disable the mouse ?

I have optical and laser mouse. The problem always appears, turned off or turned on. On laptop is all the same only with a touchpad without a mouse.



> Closing because duplicate of #992 or #900 .
> Correct me if I'm wrong

Yes, it's duplicate. How I see this is an old question and has not been fixed.

**Comment by Persei08** [comment] 2020-03-01 12:59
Yes, #992 and #900 are still open and not fixed.
