### ISSUE TITLE
Subtitle / Audio languages are gone except for English.

### ISSUE THREAD

**Issue by Darkmeteorx** [popcorntime/popcorntime#1801] opened 2020-11-09 05:01 UTC
Operating System Version:
Windows 10?

Popcorn Time Version:
Popcorn-Time-0.4.4-win64

Download date:
Last week and today

Download url (optional):
https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/artifact/build/Popcorn-Time-0.4.4-win64-Setup.exe

**Expected Behaviour**
When clicking on the Audio / Subtitles icon on a movie screen, multiple language options displayed, you can select them for download.

**Actual Behaviour**
Not sure what changed, but from yesterday when I tried downloading some movies all the subtitle options disappeared, and for Audio only English is available, I have tried to uninstall completely and reinstall, read some posts about general subtitle issues, but nothing works, there are no options anymore, just plain English for audio in all the movies and no subtitles.

I have read that you need to put an opensubtitles.org account in the options, I have tried that too but, with an old account and also created a new one, both fail to authenticate for some reason, a red cross mark appears next to the user and will not login.

**Steps to reproduce the behavior**

Go to any movie and see the Audio and subtitle options, only last week I was able to see multiple options to select. I remember to see also the Halloween theme.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
![image](https://user-images.githubusercontent.com/74168228/98501883-17de4680-2216-11eb-855a-58aa7201967d.png)

Although there are other options to get the subtitles manually, I think this version of popcorn had this really nice feature and feels bad that it's gone, hope it's only something I'm doing wrong.

Thanks for the help!

**Comment by Persei08** [comment] 2020-11-09 15:52
Hi,

For audio its normal. As far as I know all videos are in English.
For subtitles, it's empty because it require to set an account in settings as you already know.

I just reset my PCT and tried to connect it in settings and it works as expected.

Can you confirm you created your opensubtitles account from opensubtitles.org and not opensubtitles.com ?

Else can you copy paste you developer console output.

**Comment by Darkmeteorx** [comment] 2020-11-10 16:16
Yes, it is opensubtitles.org, I have reinstalled and reset PCT many times and it just doesn't connect.

I just tried again and it works now lol, I didn't change anything..., maybe I was just doing it wrong., It is working as expected now.

I could swear that I saw multiple audio options for Captain America Winter Soldier, could have been my imagination though.

Thanks!

**Comment by kiriles90** [comment] 2020-11-10 19:11
> I just tried again and it works now lol, I didn't change anything..., maybe I was just doing it wrong., It is working as expected now.

Maybe opensubtitles was down or under maintenance? It happens from time to time. Closing since the issue is solved.

**Closed as completed by kiriles90** 2020-11-10 19:11 UTC
