### ISSUE TITLE
Error Building on Ubuntu

### ISSUE THREAD

**Issue by champier** [popcorntime/popcorntime#376] opened 2016-12-01 06:54 UTC
Operating System Version:
Linux - Ubuntu 16.4

Popcorn Time Version:
3.10

Download date:
Today

#### Expected Behaviour
Compile heheh
...

#### Actual Behaviour
 Error
...

**Comment by Persei08** [comment] 2016-12-01 07:32
Maybe, it will help you to paste the terminal messages

**Comment by champier** [comment] 2016-12-01 07:40
claude@GhostProtocol:~/BlackBOX/UP$ gulp build
[09:29:11] Using gulpfile ~/BlackBOX/UP/gulpfile.js
[09:29:11] Starting 'build'...
[09:29:11] Starting 'injectgit'...
Branch: master
Commit: b307c0c5
[09:29:11] Finished 'injectgit' after 16 ms
[09:29:11] Starting 'css'...
Stylus files compiled in /home/claude/BlackBOX/UP/src/app/themes/
[09:29:14] Finished 'css' after 3.47 s
[09:29:14] Starting 'nwjs'...
Using v0.18.6 (sdk)
Create cache folder in /home/claude/BlackBOX/UP/cache/0.18.6-sdk
Using cache for: linux64
Create release folder in /home/claude/BlackBOX/UP/build/Popcorn-Time/linux64
[09:31:21] Finished 'nwjs' after 2.1 min
[09:31:21] Finished 'build' after 2.17 min
claude@GhostProtocol:~/BlackBOX/UP$ gulp run
[09:34:21] Using gulpfile ~/BlackBOX/UP/gulpfile.js
[09:34:21] Starting 'run'...
Running linux64 from cache
linux64 is not available in cache. Try running `gulp build` beforehand
[09:34:21] 'run' errored after 6.94 ms
[09:34:21] Error: spawn cache/0.18.6/linux64/nw ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Popcorn-Time exited with code -2

**Comment by team-pct** [comment] 2016-12-01 08:03
rm -rf cache
rm -rf build
rm -rf node_modules
and then
```
npm install
gulp build
gulp run
```

if it dont work then it mean i cannot reproduce

**Comment by champier** [comment] 2016-12-01 08:15
Same error !
 
claude@GhostProtocol:~/BlackBOX/UP$ gulp run
[10:15:18] Using gulpfile ~/BlackBOX/UP/gulpfile.js
[10:15:18] Starting 'run'...
Running linux64 from cache
linux64 is not available in cache. Try running `gulp build` beforehand
[10:15:18] 'run' errored after 6.55 ms
[10:15:18] Error: spawn cache/0.18.6/linux64/nw ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Popcorn-Time exited with code -2
claude@GhostProtocol:~/BlackBOX/UP$

**Comment by Persei08** [comment] 2016-12-01 08:39
This Butter issue seem related https://github.com/butterproject/butter-desktop/issues/429

edit: or maybe not :)

**Comment by Persei08** [comment] 2016-12-01 10:05
Same error for me with master and developpement branches.
>$ lsb_release -ds
Ubuntu 14.04.5 LTS

>$ uname -spr
Linux 4.2.0-42-generic x86_64

>$ nodejs -v
v6.9.1

>$ npm -v
3.10.8

>$ sudo gulp run
[10:58:08] Using gulpfile ~/devel/pct/popcorn-desktop/gulpfile.js
[10:58:08] Starting 'run'...
Running linux64 from cache
linux64 is not available in cache. Try running `gulp build` beforehand
[10:58:08] 'run' errored after 11 ms
[10:58:08] Error: spawn cache/0.18.1/linux64/nw ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Popcorn-Time exited with code -2

**Comment by ChrisAlderson** [comment] 2016-12-01 12:30
Fixed with: https://github.com/popcorn-official/popcorn-desktop/commit/43c4a8467795cb49536b034aa38803794fe9365a

**Closed as completed by ChrisAlderson** 2016-12-01 12:30 UTC

**Comment by Persei08** [comment] 2016-12-01 18:39
It's working. Thanks
