### ISSUE TITLE
Excessive memory and CPU usage while downloading file leading to swapping and stutter

### ISSUE THREAD

**Issue by JPSmeets** [popcorntime/popcorntime#1374] opened 2020-04-19 11:08 UTC
Operating System Version:
Win 10 1909 x64
4GB phys memory

Popcorn Time Version:
0.4.4.win32 
0.4.4.win64

Download date:
4/18/2020

#### Expected Behaviour
PT should limit memory and CPU usage while downloading

#### Actual Behaviour
PT uses more and more memory while downloading and also uses a lot of CPU for download speed of 75Mb/s
Memory usage leads to swapping and shutter. CPU usage leads to system becoming slow.
Combination of both leads to stutter.
After movie is downloaded everything returns to normal (memory and CPU) 
Cannot watch movie in this state. PT 0.3.1 did not have this issue.

#### Steps to reproduce the behaviour
1. Use system with 4GB phys RAM
2. Run taskmgr
3. Clean download cache
4: Watch 1080p movie
5. Observe memory and CPU usage

**Comment by team-pct** [comment] 2020-04-19 11:12
Go to settings and set Connection Limit lower

**Comment by artikweb** [comment] 2020-04-19 19:37
Duplicate of #1373

**Comment by Persei08** [comment] 2020-04-20 19:58
Duplicate of #1350, #1373

**Closed as completed by Persei08** 2020-04-20 19:58 UTC
