### ISSUE TITLE
Popcorn Time is not updating movies

### ISSUE THREAD

**Issue by Alex1087** [popcorntime/popcorntime#1698] opened 2020-09-24 08:46 UTC
It's been 3 weeks since the last update of movies, everyday I'm checking Popcorn Time but still no update. What happen to Popcorn Time now? Recently I always see a new update every week but now It's been 3 weeks since the last update.

**Comment by kiriles90** [comment] 2020-09-24 12:47
Duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1690

**Closed as completed** 2020-09-24 23:20 UTC
