### ISSUE TITLE
[UI Bug] When the default language is set to French, the settings button does not function

### ISSUE THREAD

**Issue by pctUser** [popcorntime/popcorntime#1584] opened 2020-07-30 15:00 UTC
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4-0

Download date:
7/22/2020

Download url (optional):
reddit.com/r/popcorntime

#### Expected Behaviour
The settings menu would open

#### Actual Behaviour
Stays on the current page

#### Steps to reproduce the behaviour
With popcorn time set to English, open the settings menu by clicking the gear icon on the upper right. 
Change the default language to French (Francais).
Attempt to open the settings menu again with the gear icon.
Observe that the settings menu does not open and Popcorn Time remains on the current page.

**Comment by dutchy1001** [comment] 2020-07-30 15:14
I have tried to reproduce this but when I set the language to French (Francais) the gear icon works, I also tried "dutch" (Nederlands) which also did work as intended.

Update to the latest dev build (from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**) and see if the issue is still happening, if fixed please close this post.

**Comment by kiriles90** [comment] 2020-07-31 00:01
This was fixed with https://github.com/popcorn-official/popcorn-desktop/pull/1455 (May 21, 2020)

**Closed as completed** 2020-07-31 01:10 UTC
