### ISSUE TITLE
Subtitles don't show on Smart TV

### ISSUE THREAD

**Issue by CViniciusSDias** [popcorntime/popcorntime#1114] opened 2020-01-03 19:20 UTC
Operating System Version:
Linux

Popcorn Time Version:
3.10

Download date:
Jan 03 2019

#### Expected Behaviour
When dropping a subtitle file (.srt) to the player when streaming to (Samsung) Smart TV, the subtitles should be shown.
...

#### Actual Behaviour
Subtitles are not displayed when streaming to Smart TV
...

#### Steps to reproduce the behaviour

1. In the settings, select Brazilian Portuguese as the default subtitles language
2. Choose a movie (in my case, Aladdin)
3. Select the TV and hit "Watch now"
4. Drop the .srt file to the player once it starts streaming

#### Console output

This is what I get from console when I drop the subtitle in the Popcorn Time window:
```
[DEBUG] Drag init app.js:6
[DEBUG] Drag completed app.js:605
could not handle DragEvent
altKey
:
false
bubbles
:
true
button
:
0
buttons
:
0
cancelBubble
:
false
cancelable
:
true
clientX
:
651
clientY
:
688
composed
:
true
ctrlKey
:
false
currentTarget
:
null
dataTransfer
:
DataTransfer
defaultPrevented
:
true
detail
:
0
eventPhase
:
0
fromElement
:
null
isTrusted
:
true
layerX
:
651
layerY
:
688
metaKey
:
false
movementX
:
0
movementY
:
0
offsetX
:
651
offsetY
:
688
pageX
:
651
pageY
:
688
path
:
Array[7]
relatedTarget
:
null
returnValue
:
false
screenX
:
651
screenY
:
688
shiftKey
:
false
sourceCapabilities
:
InputDeviceCapabilities
srcElement
:
div#drop-mask
target
:
div#drop-mask
timeStamp
:
528980.5650000001
toElement
:
div#drop-mask
type
:
"drop"
view
:
Window
which
:
1
x
:
651
y
:
688
__proto__
:
DragEvent
window.ondrop @ app.js:605
```

**Comment by kiriles90** [comment] 2020-09-26 20:44
@Persei08 duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1495, close please

**Closed as completed** 2020-09-28 17:39 UTC
