### ISSUE TITLE
Inform how many seasons of a certain show are available on PT and how many seasons has been released for that show

### ISSUE THREAD

**Issue by popcornenthusiast** [popcorntime/popcorntime#392] opened 2016-12-07 13:19 UTC
(See issue #389 and issue [68](https://github.com/popcorn-official/popcorn-api/issues/68) on popcorn-api)

The way how PT tells the user how many seasons are available on PT is definitely misleading and would be better to show how many seasons are available and how many seasons have been released for a certain show, changing "X Seasons [Available seasons]" for "X [Available seasons]/Y seasons [Released seasons]".

**Comment by AlJohri** [comment] 2016-12-08 00:03
Duplicate of #364.

**Closed as completed** 2016-12-24 19:12 UTC
