### ISSUE TITLE
Keyboard issues in CI version

### ISSUE THREAD

**Issue by Abhinav1217** [popcorntime/popcorntime#763] opened 2018-04-20 11:29 UTC
Operating System Version:
  Manjaro Linux (Gnome) 64 bit updated Daily.

Popcorn Time Version:
  Head f3135466, downloaded from https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/lastSuccessfulBuild/
 
Download date:
Yesterday at the time of this writing. 19/04/2018

#### Expected Behaviour
Use keyboard for faster navigation. 

#### Actual Behaviour

Keyboard controls mostly not working. There have been some time when it felt it is working, but as soon as I press enter and next page is loaded, it stops working. It hasn't worked on the Butter Player yet. I have to use VLC playback.
...

#### Steps to reproduce the behaviour

1. Install Manjaro Linux and Update it.
2. Download popcorn time from ci and install it in /opt ( I also tried it from `/home/abhinav/popcorn` incase this was some permission issue )
3. Launch Popcorn time and try to traverse it using keyboard.

_**Side Notes: **_

The version I used to download from popcorntime.sh website, used to store torrents in seperate folders based on their hash ( like /torrent/Popcorn Time/<torrent hash>/<files> ), but this CI version is keeping it in the download location root ( like /torrent/Popcorn Time/<files> ). Is this expected? I can't use old version because it has stopped connecting to trakt.tv .

There are actually few more issues regarding custom subtitle ( Can not load custom subtitle )and Chromecast playback ( Video is fine but sound is not there ), Should I report them as a seperate issue?

**Comment by Persei08** [comment] 2018-04-21 00:41
Duplicate: #725

**Comment by ChrisAlderson** [comment] 2018-04-28 18:57
Duplicate of #725, thanks @Persei08

**Closed as completed by ChrisAlderson** 2018-04-28 18:57 UTC
