### ISSUE TITLE
Pressing X doesn't close the window.

### ISSUE THREAD

**Issue by ghost** [popcorntime/popcorntime#1501] opened 2020-05-31 17:57 UTC
The X which sits at the top right corner doesn't work as expected. The only way to close the app seems to be through the Task manager from Windows.
Windows 10 Pro N, 0.4.4

**Comment by dutchy1001** [comment] 2020-05-31 18:57
guess you havent read the pinned topic on top here about the issue??

**Comment by Persei08** [comment] 2020-05-31 20:35
Duplicate of #1280

**Closed as completed by Persei08** 2020-05-31 20:35 UTC
