### ISSUE TITLE
[possible leak] nwjs consuming too much memory / CPU, after some time of idle

### ISSUE THREAD

**Issue by gladykov** [popcorntime/popcorntime#1299] opened 2020-04-10 15:21 UTC
Operating System Version:
Windows 10 Pro

Popcorn Time Version:
0.4.0-0

1. Open app
2. Navigate to Series
3. Leave popcorn window open and do other stuff

Result:
Memory usage starts to grow steadily. Also nwjs is consumg 5- 10% of CPU, while Opera with few tabs open consumes around 2%. After some time (~15 - 30 minutes) CPU load is enough (> 25%) to trigger aggresive cooling. Attaching heaptimeline from the moment, when processor is hot. 

[Heap-20200410T160103.zip](https://github.com/popcorn-official/popcorn-desktop/files/4462143/Heap-20200410T160103.zip)

This happend to me more than once, always in same scenario.

**Comment by kamilko** [comment] 2020-04-14 20:59
The same on macos. After 1h of running, 8GB real memory is used.

**Comment by cghislai** [comment] 2020-04-14 21:41
version 0.4.4, on linux, playing with the embedded player and subtitles.
After 2min, one exe process with the --ngsw flag consumes 100% CPU (on 1 thread), embedded player becomes unresponsive.
Inspecting both pages available on port 9222 with chrome does not detect any cpu usage nor unusual activity (lots of warnings, but not spamming endlessly).

Using an external player, I see no issue after ~10min so far.

On 0.4.3, i could work around this issue by closing and restarting the app, which never became unresponsive.

**Comment by JoecMit** [comment] 2020-04-15 00:02
Version 0,4,4 - Win 10

Same problem, timed it in movie duration, starting the movie RAM usage was around **134,6 MB** after 01:48:36 was up to **678,2 MB**, after 15 minutes of next movie the app was so laggy and unsresponsive so i checked again and **5,874 MB** was on usage by PT

**Comment by br3eze** [comment] 2020-04-16 10:58
> Version 0,4,4 - Win 10
> 
> Same problem, timed it in movie duration, starting the movie RAM usage was around **134,6 MB** after 01:48:36 was up to **678,2 MB**, after 15 minutes of next movie the app was so laggy and unsresponsive so i checked again and **5,874 MB** was on usage by PT

19+ Gb after a night minimized with already loaded paused film. 4.4 Artix (Arch) Linux x64.

**Comment by kiriles90** [comment] 2020-09-26 20:32
@Persei08 duplicate of #1373, close this please

**Comment by Persei08** [comment] 2020-09-28 17:38
Duplicate of #1373 ... I know #1373 was open after this one but seem there is infos there.

**Closed as completed by Persei08** 2020-09-28 17:38 UTC
Labels: bug, help wanted
