### ISSUE TITLE
Updating movies

### ISSUE THREAD

**Issue by LP4924** [popcorntime/popcorntime#1757] opened 2020-10-23 08:37 UTC
Hi All

I realise that this issue have been covered before but this has been an issue for a while now (2 months +)

I have noticed for a while now that PCT is not updating at all. I have uninstalled and reinstalled and even installed the previous version but to no avail. Any advice please.

regards LP4924 (huge fan)

**Comment by dutchy1001** [comment] 2020-10-23 08:45
this is a known issue already

duplicate of #1690

**Closed as completed** 2020-10-25 14:43 UTC
