### ISSUE TITLE
no subtitle 

### ISSUE THREAD

**Issue by eshmk** [popcorntime/popcorntime#1665] opened 2020-09-02 03:36 UTC
Operating System Version: Mac 

Popcorn Time Version:4.4

Download date:09/01/2020

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment] 2020-09-02 08:07
duplicate of #1664

**Closed as completed** 2020-09-02 11:56 UTC
