### ISSUE TITLE
Please wait is looping forever after latest update installation

### ISSUE THREAD

**Issue by vRITHNER** [popcorntime/popcorntime#1321] opened 2020-04-14 07:31 UTC
Operating System Version:
Windows 10 insider

Popcorn Time Version:
0.4.3

Download date:
04-14-2020

#### Expected Behaviour
Start it and after few seconds, see all movies and shows

#### Actual Behaviour
The please is looping forever and nothing displayed
...

#### Steps to reproduce the behaviour
Start the program

**Comment by carolinemo** [comment] 2020-04-14 07:57
Exactly, me too, the looping never stops

**Comment by carolinemo** [comment] 2020-04-14 07:58
i tried to restart it but nothing changes

**Comment by SahilTourani** [comment] 2020-04-14 08:57
Yeah facing the same problem on Mac machine. I faced this problem on the previous version too. 04.1. Was just working last night

**Comment by dutchy1001** [comment] 2020-04-14 09:02
Have you tried updating to build 407, you can find this version [**here**](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/407/).
This is a differenrt version than on the official download page.

**Comment by SahilTourani** [comment] 2020-04-14 09:04
@dutchy1001 im assuming you are not facing this issue? I also reinstalled to 0.4.1 and i see the same issue of this non stop loading blue circle

**Comment by dutchy1001** [comment] 2020-04-14 09:14
Mine works fine with build 407
I use windows 10 build 18363.720

**Comment by SahilTourani** [comment] 2020-04-14 09:30
@dutchy1001 hmm, so did you ever face this issue? and did 407 resolve it? Just wondering why last night it was working fine for me

**Comment by dutchy1001** [comment] 2020-04-14 09:41
As I hadn't watched PCT today yet and last time all was still fine, mine is doing the same now. This looks like the torrent connection they use in PCT is failing to connect. 
This could have several reasons,
1. Server maintenance 
2. DDos attack
3. DMCA takedown (of the torrents)

As PCT doesn't store the media itself they are depended on the "torrents links".

**Comment by wenrei09** [comment] 2020-04-14 12:30
dutchy1001 Which of these links should I download? I have a Mac
![Captura de pantalla 2020-04-14 a las 14 20 58](https://user-images.githubusercontent.com/23667052/79225078-7b5ced00-7e5c-11ea-8f08-7c5e4345852e.png)

**Comment by asadmalik** [comment] 2020-04-14 13:47
Seems to be fixed after 0.4.4 for me.

**Comment by dutchy1001** [comment] 2020-04-14 13:48
@wenrei09 
you should use the updated build 409, get it [**here**](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/409/) and use the OSX64, not sure you need the update or the Popcorn-time one (I'm not an Apple fan or user)

**Comment by cmarinse** [comment] 2020-04-14 20:42
> 
> 
> @wenrei09
> you should use the updated build 409, get it [**here**](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/409/) and use the OSX64, not sure you need the update or the Popcorn-time one (I'm not an Apple fan or user)

link not working

**Comment by dutchy1001** [comment] 2020-04-14 21:24
@cmarinse 
link works for me no problem

**Comment by PinkiePie1991** [comment] 2020-04-16 11:56
Good Day, 
Can someone please help me with Popcorn Time thats just stuck loading.
I used Popcorn Time up until 13 April and then it updated and now I cant use it, it just loads the whole time.I have restarted the app numerous time as wel as downloaded and installed different versions but I still have the same problem.Please help.
I dont know anything about IT so I dont understand your previous comments.
I have windows 7 64bit
![image](https://user-images.githubusercontent.com/63789981/79453479-0c150380-7fea-11ea-9c9a-16e25022a235.png)

**Comment by dutchy1001** [comment] 2020-04-16 12:42
@PinkiePie1991 
Have you used any link inside this post to update your Popcorn-Time?
If not try this version **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/413/)**

**Comment by PinkiePie1991** [comment] 2020-04-16 13:06
My avast detected the file as there may be something wrong with the file?
![image](https://user-images.githubusercontent.com/63789981/79459414-872ee780-7ff3-11ea-8fd8-478ffc4b16ca.png)

**Comment by team-pct** [comment] 2020-04-16 13:33
If it crack let us know :D

**Comment by dutchy1001** [comment] 2020-04-16 14:49
my Avast didnt give me this message, but I got the zip file instead.

EDIT:
after dowloading the same and scanned it with Avast I did not get any message about being dangerous.

**Comment by PinkiePie1991** [comment] 2020-04-16 15:06
I installed the file and opened Popcorn Time but it still does the same.
Did i download the correct one?
![image](https://user-images.githubusercontent.com/63789981/79472854-a2eeb980-8004-11ea-9f8e-d3005343cb21.png)

**Comment by PinkiePie1991** [comment] 2020-04-16 15:08
which one must i download?
![image](https://user-images.githubusercontent.com/63789981/79473014-d5001b80-8004-11ea-8a0c-4cb1e3f00928.png)

**Comment by team-pct** [comment] 2020-04-16 15:09
Win32 setup or win64 setup should work , in worst cast scenario get the zip

**Comment by PinkiePie1991** [comment] 2020-04-17 07:48
My Popcorn Time started working again this morning :)

**Comment by Rowda109** [comment] 2020-04-18 12:59
It doesn't working. 
![image](https://user-images.githubusercontent.com/63377236/79638315-ef1d3380-8195-11ea-9012-78b0b4aba8a6.png)

**Comment by dutchy1001** [comment] 2020-04-18 15:19
@Rowda109 
not sure were you got this, but you gave no info what link you used or anything to work with.

**Comment by VulcanTourist** [comment] 2020-04-20 02:58
> 
> 
> Seems to be fixed after 0.4.4 for me.

It is NOT fixed by 0.4.4-0 for me.  The April Fools' Day 0.4.1 update broke it, and every time I've tried to use it (not daily) thereafter it just hangs/spins.  0.4.1 was the first version that was ever advertised (with a toast-like notification) from within the application itself, and after allowing the self-update it's the first version ever to be broken like this.  I grabbed the version 0.4.4 installer EXE (Windows 64-bit) from the site just now, and version 0.4.4 has not fixed it.  I can't help thinking that all that self-promotional silliness changing all the movie titles to include "Popcorn Time" in them is somehow the cause of this.

**Comment by dutchy1001** [comment] 2020-04-20 08:36
@VulcanTourist 
Try the the direct link for the latest version **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/416/)**, that is different then on the main site.

**Comment by Persei08** [comment] 2020-04-20 23:06
Ok, i close this because its related to previous version.
The previous api domain was taken down and it's causing this issue on older versions.

You need to update to v4.4 because this one use some new api domains which were deployed.

You can download last version of PT here: 

- Windows: https://popcorntime.app/windows
- MacOS: https://popcorntime.app/mac
- Linux: https://popcorntime.app/linux

**Closed as completed by Persei08** 2020-04-20 23:06 UTC
