### ISSUE TITLE
Purple and Green Color rendering

### ISSUE THREAD

**Issue by Zubbbz** [popcorntime/popcorntime#2514] opened 2022-06-17 06:59 UTC
I think I have the same issue as this person [here](https://github.com/popcorn-official/popcorn-desktop/issues/1409).

![image](https://user-images.githubusercontent.com/37497090/174242586-7fead4d2-6b60-468a-bbfb-75b7daf51011.png)

Some relevant Reddit articles [1](https://www.reddit.com/r/PleX/comments/r1t3hy/green_purple_tint_with_dv_dolby_vision/hm24082/), [2](https://www.reddit.com/r/PleX/comments/r1t3hy/green_purple_tint_with_dv_dolby_vision/hm24082/) to the issue.

This is probably the best [solution](https://www.reddit.com/r/PleX/comments/r1t3hy/comment/hrhj9q2/?utm_source=share&utm_medium=web2x&context=3). If there was a way to view these files as intended on non DV displays, that would be great aswell.

**Comment by kiriles90** [comment] 2022-06-17 11:58
It would have been helpful if you didnt bypass the required fields when you open a post.. Anyway assuming you are using the official app, and the latest version.., then the issue is with your device. An OS or a driver issue. If you've checked/updated those and nothing changed and Popcorn Time's native player still wont play nice with your setup, try a supported external player (click the `?` in the menu next to the watch now button to see the list)  

Closing this as its not an issue with the app but feel free to comment below with more details if you're still having the issue.

**Closed as completed by kiriles90** 2022-06-17 11:58 UTC

**Comment by Zubbbz** [comment] 2022-06-18 01:17
The issue is that Dolby Vision files only support playback on displays that support Dolby Vision. The solution is simple. I have tried on multiple os's with multiple drivers and different video players. All have the same issue. That is because of the formatting of these problematic files is DV 5.2 which cannot be parsed into a normal stream by any available video players or codecs. The solution would be very easy, add an option to filter out DV files from torrent selection or find a way to parse and view DV 5.2 files on nom DV screens.

**Comment by Zubbbz** [comment] 2022-06-18 01:19
Also sorry for not using correct issue formatting, for whatever reason, it didn't appear when I clicked 'New issue'

**Comment by kiriles90** [comment] 2022-06-18 03:40
The issues that you linked arent dolby vision related. Even the buttons in the app are the wrong color. As for everything else.. we still cant replicate or verify anything since you arent giving us a version number, an OS and some content with the issue as an example. You even cropped the UI out of the screenshot to make any identificaton that way impossible..
