### ISSUE TITLE
Add the possibility to sort movies by rating considering a minimum number of votes (>=200)

### ISSUE THREAD

**Issue by popcornenthusiast** [popcorntime/popcorntime#390] opened 2016-12-07 13:17 UTC
(See issue #389)

This would make for a better sorting method, as completely unknown movies with a low number of votes wouldn't appear.

**Comment by AlJohri** [comment] 2016-12-08 00:03
Duplicate of #358.

**Closed as completed** 2016-12-24 19:12 UTC
