### ISSUE TITLE
Watch now button does not work at all

### ISSUE THREAD

**Issue by Lsk-Snn** [popcorntime/popcorntime#1853] opened 2020-11-23 20:02 UTC
Hi, I have Windows 8 and Pop corn time started not to work properly. I could not watch certain movies and series. I uninstalled and reinstalled version 4.4 and now nothing works.

The Watch now button just wouldn't work. When I click on it nothing happens.

Operating System Version:

Popcorn Time Version:

Download date:

Download url (optional):

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by Persei08** [comment] 2020-11-23 20:13
Title is misleading :/

The "watch now" button issue is already fixed in dev builds. 

~~We kept the related issue ( #1280 ) pinned on the board for people to find it easily.~~

~~Duplicate of #1280~~

Edit: My bad, the pinned issue is another one, but we have lot of "watch now" button issues already closed

**Closed as completed by Persei08** 2020-11-23 20:13 UTC

**Comment by Lsk-Snn** [comment] 2020-11-23 20:18
Well not true.
#1280<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpopcorn-official%2Fpopcorn-desktop%2Fissues%2F1280&data=04%7C01%7C%7C992d77626a3a4bcec78808d88fec5384%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637417592451837062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jgTm%2B8P4zn7Y2XckQ3vX9Ibmt34ZpHSSU4CDXgEwpOk%3D&reserved=0> is about Popcorn time won’t close.
My problem is I can’t watch anything. So?

De : Persei08 <notifications@github.com>
Envoyé : lundi 23 novembre 2020 21:14
À : popcorn-official/popcorn-desktop <popcorn-desktop@noreply.github.com>
Cc : Lsk-Snn <liuskasanna@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [popcorn-official/popcorn-desktop] Watch now button does not work at all (#1853)


Title is misleading :/

The "watch now" button issue is already fixed in dev builds. We kept the related issue ( #1280<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpopcorn-official%2Fpopcorn-desktop%2Fissues%2F1280&data=04%7C01%7C%7C992d77626a3a4bcec78808d88fec5384%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637417592451827065%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k6ZpkL2QlHoVZbsh0nvsHKb6PxtG9t%2BQFD1LGk70PBw%3D&reserved=0> ) pinned on the board for people to find it easily.

Duplicate of #1280<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpopcorn-official%2Fpopcorn-desktop%2Fissues%2F1280&data=04%7C01%7C%7C992d77626a3a4bcec78808d88fec5384%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637417592451837062%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jgTm%2B8P4zn7Y2XckQ3vX9Ibmt34ZpHSSU4CDXgEwpOk%3D&reserved=0>

**Comment by dutchy1001** [comment] 2020-11-23 21:08
> I uninstalled and reinstalled version 4.4 and now nothing works.

You haven't mentioned which build you have re-installed. If you installed the same version you used then of course it will give the same issue's again. 
Try the latest dev build ( **[Build 442](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)** at time of writing) and see if the issue's still happen.

**Comment by Persei08** [comment] 2020-11-23 21:12
@Lsk-Snn  I corrected. 
I made a mistake about the pinned issue. Because these "watch now" button and "popcorn time don't close" issues are the more duplicated ones.

What you describe is the "watch now" button, and is already fixed in latest dev builds. Thx

**Comment by Lsk-Snn** [comment] 2020-12-10 14:55
Hello,

I have done as you suggested. I do not have those problems anymore.
But still most of the time it wouldn’t work. Either it doesn’t open, or doesn’t connect or it is extremely slow (my internet connection is good).
So, I do not know what to do.

De : dutchy1001 <notifications@github.com>
Envoyé : lundi 23 novembre 2020 22:08
À : popcorn-official/popcorn-desktop <popcorn-desktop@noreply.github.com>
Cc : Lsk-Snn <liuskasanna@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [popcorn-official/popcorn-desktop] Watch now button does not work at all (#1853)


I uninstalled and reinstalled version 4.4 and now nothing works.

You haven't mentioned which build you have re-installed. If you installed the same version you used then of course it will give the same issue's again.
Try the latest dev build ( Build 442<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fci.popcorntime.app%2Fjob%2FPopcorn-Time-Desktop%2FlastStableBuild%2F&data=04%7C01%7C%7C0684be0504654186cead08d88ff3e571%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637417624967030984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=y4Mrh%2BFbtHeqff3nrcctiNR%2F4tV3fxcuVDa72%2FQmORk%3D&reserved=0> at time of writing) and see if the issue's still happen.

**Comment by dutchy1001** [comment] 2020-12-10 15:15
Can you make a screenshot of the info tab?  (and then focus on the right bottom were it says "Love in the time of Corona"

**Comment by Lsk-Snn** [comment] 2020-12-18 20:00
I don’t know what the info tab is. I don’t think I get it.
Either it wouldn’t open, you know the cercle going around endlessly trying to connect.
Or if it opens and I can select a movie or a series it would get stuck on the connection page without downloading.

De : dutchy1001 <notifications@github.com>
Envoyé : jeudi 10 décembre 2020 16:16
À : popcorn-official/popcorn-desktop <popcorn-desktop@noreply.github.com>
Cc : Lsk-Snn <liuskasanna@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [popcorn-official/popcorn-desktop] Watch now button does not work at all (#1853)


Can you make a screenshot of the info tab? (and then focus on the right bottom were it says "Love in the time of Corona"

**Comment by Persei08** [comment] 2020-12-20 01:08
@Lsk-Snn the info tab is the "info" icon on right toolbar also know as "about" view or in french "à propos"

But it seem you no longer have bug here, What you describe seem to be network related issues.

You should better ask some help on the forum https://discuss.popcorntime.app/ or subreddit https://www.reddit.com/r/PopCornTimeApp/
