### ISSUE TITLE
Popcorn time on Ubuntu 18.04 does not play anything after vlc crash

### ISSUE THREAD

**Issue by sub-1337** [popcorntime/popcorntime#1108] opened 2019-12-21 02:24 UTC
Operating System Version:
Ubuntu 18.04 

Popcorn Time Version:
0.3.10-Linux-64

Download date:
Dec 21

#### Actual Behaviour
After critical exit from vlc it does not play again. It just shows message "ready" after pressing play button.

#### Steps to reproduce the behaviour
1. Click play with vlc.
2. Get vlc bug - showing icon instead of video. (only mine bug, you can probably simulate it by killing it)
3. Close vlc.
4. Try to re-lunch - get "downloading subtitles" and "ready" sign and nothing more.

**Comment by Persei08** [comment] 2020-02-13 21:51
Can't reproduce.

Ubuntu 18.04 64bits - VLC 3.0.8 (3.0.8-0ubuntu1  - Ubuntu:18.04/bionic-updates)

at step 2:
- If I kill PT, VLC start to play what is already downloaded and then stop to play.
- If I kill VLC PT detect it and come back to movies details page.

What is your VLC version ?  
Is it installed via snap, flatpak or apt ?

**Comment by Persei08** [comment] 2020-03-27 04:20
I close this one, if someone able to reproduce. please provide the necessary steps. Thx

**Closed as completed by Persei08** 2020-03-27 04:20 UTC
