### ISSUE TITLE
No subtitles on tv shows!

### ISSUE THREAD

**Issue by buzzer-re** [popcorntime/popcorntime#272] opened 2016-10-24 23:10 UTC
Operating System Version:
Linux

Popcorn Time Version:
Popcorn-Time-0.3.9

Download date:
one week ago
#### Expected Behaviour

Show subtitles on tv shows
...
#### Actual Behaviour

I cant see any subtitles on tv shows! in movies works fine but i cant see in tv shows! 
...
#### Steps to reproduce the behaviour

1. open popcorntime
2. go to tv shows
3. choose one
4. dont show subtitles

**Comment by giuligi** [comment] 2016-10-25 20:03
same thing

**Comment by markoreaper** [comment] 2016-10-26 13:29
Same thing here.

OS
Win 7....

**Comment by gordislav** [comment] 2016-10-26 14:57
Same here

OS Version:
Windows 10 v1607

When I click on any movie, I can see the subtitle selection drop down menu on the lower right side of the window, and while the movie plays I can change the shown subtitle to any other available, or I can load the custom sub.
There's no subtitle drop down menu on any tv show, and I can only load the custom subs while the show is played

I also noticed that I can't choose any subtitles except load the custom one if I play the movie/tv show/anything using the magnet link or drag'n'drop torrent file, even if there's a sub on opensubtitles for that exact version. I even tried playing the movie from API, checking that there is a menu of subtitles, and then playing the same torrent as the one from API, but using the magnet link (and torrent file drag'n'drop), and there was no subtitles in menu, there was only the 'custom' option.

All this above was working fine in 0.3.8

I also can't log in to opensubtitles from options. Logging in is working from web and I have the right username and password. Not sure if this is related to previous issues

**Comment by ChrisAlderson** [comment] 2016-10-26 17:33
Duplicate of #227 and #251

**Closed as completed by ChrisAlderson** 2016-10-26 17:33 UTC
