### ISSUE TITLE
The app wont close, no subtitles again.

### ISSUE THREAD

**Issue by Andres2903** [popcorntime/popcorntime#1284] opened 2020-04-08 23:49 UTC
Operating System Version:
 Windows 10

Popcorn Time Version:
4.3
Download date:
8/04/2020

#### Expected Behaviour
Close like any other app. Put normal subtitles option like the past.
...

#### Actual Behaviour
It's still open, no subtitles at all.
...

**Comment by kiriles90** [comment] 2020-04-09 08:33
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by LuisCRSousa** [comment] 2020-04-11 16:47
> Duplicate #1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/
> 
> (you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

Not fixed

**Comment by kiriles90** [comment] 2020-04-11 16:53
@LuisCRSousa its fixed for everyone who can read

**Comment by LuisCRSousa** [comment] 2020-04-11 17:00
> @LuisCRSousa its fixed for everyone who can read

I'm using the last version and I made the login. So, not fixed.

**Comment by kiriles90** [comment] 2020-04-11 17:23
@LuisCRSousa you are not using the last version I say in every single comment UPDATE TO BUILD 407. You are using version 0.4.3 aka build 406.

**Comment by LuisCRSousa** [comment] 2020-04-11 17:44
> @LuisCRSousa
> I say in every single comment **UPDATE TO BUILD 407**.
> **You are not using the last build** you are using version 0.4.3 aka build 406.
> 
> So, fixed..

I had build 407 installed.
But. I've unnistalled and installed again and it worked. Sorry :)

**Comment by Persei08** [comment] 2020-04-12 23:04
Duplicate of #1252 
And duplicate of #1280 too

**Closed as completed by Persei08** 2020-04-12 23:04 UTC
