### ISSUE TITLE
Eteindre

### ISSUE THREAD

**Issue by mommarin22** [popcorntime/popcorntime#1451] opened 2020-05-03 21:42 UTC
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by mommarin22** [comment] 2020-05-03 21:46
Bonjour,
je n’arrive pas à fermer la nouvelle version!!
Bug ou mauvaise version?
Merci
0.4.4-0 "Love in the Time of Corona" Beta - HEAD (b2007344)

**Comment by Persei08** [comment] 2020-05-03 23:31
Duplicate of #1280

**Closed as completed by Persei08** 2020-05-03 23:31 UTC
