### ISSUE TITLE
Legendas Sumiram... Quando vocês consertarão?

### ISSUE THREAD

**Issue by Jordania0112** [popcorntime/popcorntime#1270] opened 2020-04-06 23:27 UTC
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...

#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by kiriles90** [comment] 2020-04-07 06:51
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by Persei08** [comment] 2020-04-08 11:04
Duplicate of #1252

**Closed as completed by Persei08** 2020-04-08 11:04 UTC
