### ISSUE TITLE
Popcorntime fails to open on Fedora 35 fresh install

### ISSUE THREAD

**Issue by zlatedam** [popcorntime/popcorntime#2368] opened 2021-12-27 11:53 UTC
So i have installed popcorntime many times on a fresh install of fedora 35, but this time when opening the popcorntime app it doesn't open anything. I have tried using popcorn-time command in terminal to open it but it returns this error. 

[7374:7374:1227/225124.329700:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: AuthServerAllowlist
[7374:7374:1227/225124.378239:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: AuthServerAllowlist
[7374:7402:1227/225124.404580:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[7416:7416:1227/225124.444354:FATAL:nw_content_renderer_hooks.cc(53)] Failed to load node library (error: libatomic.so.1: cannot open shared object file: No such file or directory)
#0 0x7f5e899b7db9 <unknown>

I have installed nodejs, and any other packages that i could think that are required from this message but i am not experienced enough to solve this issue, any help is appreciated. 

-- i have also cleared the download folders and files that are created when installing popcorntime for the first time and even tried fresh installs multiple times but nothing seems to fix it.

**Comment by kiriles90** [comment] 2021-12-27 13:37
What version did you install? How/where did you get it from?
@ivan1986 any ideas?

**Comment by ivan1986** [comment] 2021-12-27 14:04
Failed to load node library (error: libatomic.so.1: cannot open shared object file: No such file or directory

**Comment by zlatedam** [comment] 2021-12-27 14:20
> What version did you install? How/where did you get it from? @ivan1986 any ideas?

I installed the newest version and followed the instructions for the linux install on the homepage, (using wget, creating the desktop entry file etc)

**Comment by kiriles90** [comment] 2021-12-27 15:11
https://github.com/popcorn-official/popcorn-desktop#linux---debianubuntu-based-distros the first paragraph and @ivan1986's reply.

**Comment by zlatedam** [comment] 2021-12-27 16:19
All the packages listed have been installed on my system, have double checked and Triple checked that they were all installed correctly.

**Comment by kiriles90** [comment] 2021-12-27 17:14
Clean install Popcorn TIme again then if they are missing install them using the commands in the Readme. The error above is pretty clear. It cant find libatomic.

**Comment by zlatedam** [comment] 2021-12-27 17:19
Package libatomic_ops-7.6.10-8.fc35.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!


As previously stated i made sure i had all the dependencies and have clean installed multiple times.

**Comment by ivan1986** [comment] 2021-12-27 17:25
https://rpmfind.net/linux/rpm2html/search.php?query=libatomic.so.1

https://rpmfind.net/linux/RPM/fedora/devel/rawhide/x86_64/l/libatomic-11.2.1-7.fc36.i686.html
https://rpmfind.net/linux/RPM/fedora/devel/rawhide/x86_64/l/libatomic_ops-7.6.12-1.fc36.i686.html

looks like you need other package

**Comment by zlatedam** [comment] 2021-12-27 17:58
Installed all the linked packages there, popcorntime app still does nothing when clicking on it to launch, popcorn-time in terminal shows [10260:10260:1228/045715.247481:ERROR:configuration_policy_handler_list.cc(90)] Unknown policy: AuthServerAllowlist
Opening in existing browser session.


& thats it.

**Comment by kiriles90** [comment] 2022-01-13 23:22
@zlatedam any news with this?

**Comment by zlatedam** [comment] 2022-01-14 00:09
Nope, i just ended up reinstalling fedora for other reasons and it fixed itself.

**Comment by kiriles90** [comment] 2022-01-14 00:29
I see, good news then. Probably something down the node rabbit-hole went wrong from the first time then kept bugging things imho..

I guess we can close this issue since it was an isolated incident that we will probably never be able to confirm the cause for since the OS was reinstalled.

**Closed as completed by kiriles90** 2022-01-14 00:29 UTC

**Comment by B0ByPop** [comment] 2022-01-28 18:38
I had to install PCT after a clean F35 installation and I struggled with the same issue
After installing several mentioned package (of the readme guidelines)
I didn't found the right libatomic one, so after searching for it
`dnf search libatomic`

and eventually installed this one like that
`dnf install libatomic-static.x86_64`

hope it will help others
