### ISSUE TITLE
cannot find subtitles 

### ISSUE THREAD

**Issue by davyah** [popcorntime/popcorntime#1371] opened 2020-04-18 23:38 UTC
Operating System Version:
windows 10

Popcorn Time Version:
latest version 

Download date:
the update came automatically

#### Expected Behaviour
there is an option to find subtitles inside the application
...

#### Actual Behaviour
just can't find subtitles either before playing and while playing the video, i have to search and download manually and add it to the player.
...

#### Steps to reproduce the behaviour
i dont know why it isnt working

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment] 2020-04-19 11:00
Here we go again with not READING the issue's posted already.
There is even a "**pinned**" post on top about **SUBTITLES** .
A fix is explained in #1318 (the pinned one on top).

Duplicate of #1317 #1313 #1312 #1302

**Closed as completed** 2020-04-19 11:11 UTC
