### ISSUE TITLE
PopcornTime does not close properly

### ISSUE THREAD

**Issue by dollhaus** [popcorntime/popcorntime#1354] opened 2020-04-16 20:32 UTC
On Win7, Win8.1EIP, and Win10, the Butter window does not close on clicking the close icon in the top right corner. Occasionally, the window will close but the processes will be left running. The only way to properly close the app is to close the four(!) nwjs processes that the application spawns. 

This behaviour is not replicated on Win7 SP1, which is the operating system of my home cinema, but is present on SP2, as well as subsequent releases of Windows across multiple platforms.

Furthermore, the textures of the window control buttons are mis-shapen and oversized, bleeding out of their areas.

**Comment by dutchy1001** [comment] 2020-04-16 20:50
Duplicate  of #1280

**Comment by dutchy1001** [comment] 2020-04-19 11:06
This should be fixed in build 415, get it from **[here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/415/)**

**Comment by Persei08** [comment] 2020-04-19 18:33
Duplicate of #1280

**Closed as completed by Persei08** 2020-04-19 18:33 UTC
