### ISSUE TITLE
Subtitle not available

### ISSUE THREAD

**Issue by jordirar** [popcorntime/popcorntime#1292] opened 2020-04-09 17:05 UTC
Operating System Version:

Windows 10
Popcorn Time Version:

0.4.3.0
Download date:

08/04/2020
#### Expected Behaviour

...
When the start movie, the subtitles not available. All the languages.
#### Actual Behaviour

...

#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by dutchy1001** [comment] 2020-04-09 18:06
guess you didn't read the previous post #1291  very well and checked the other posts mentioned in there

**Comment by Persei08** [comment] 2020-04-12 22:50
Duplicate of #1265

**Closed as completed by Persei08** 2020-04-12 22:50 UTC
