### ISSUE TITLE
Popcorn should let selection of custom subtitle on Series section before playing

### ISSUE THREAD

**Issue by osrl** [popcorntime/popcorntime#1259] opened 2020-04-04 22:48 UTC
Operating System Version:
Mac

Popcorn Time Version:
0.4.3

Download date:
04.04.2020

#### Expected Behaviour
I've managed to load a custom subtitle by triggering `subtitle:convert` in `handleSubtitles` method in streamer.js instead of downloading a new subtitle. But I thing custom subtitle should be an option before playing the show, like in movies section.

#### Actual Behaviour
Currently, only option to add custom subtitle is using player buttons. This prevents custom subs on DLNA. DLNA streaming doesn't have option to select a custom sub.

**Comment by kiriles90** [comment] 2020-09-26 16:01
@Persei08 duplicate of #1540 , close please

**Closed as completed** 2020-09-26 16:01 UTC
