### ISSUE TITLE
Cant close the application

### ISSUE THREAD

**Issue by 1mamute** [popcorntime/popcorntime#1725] opened 2020-10-05 03:47 UTC
Operating System Version:

Windows 10 full updated

Popcorn Time Version:

Using 0.4.4.0

Download date:

It's been 1 or 2 years ago.

Download url (optional):

https://popcorntime.app/

#### Expected Behaviour

Simply close the application when I click the X button in the top right corner.

#### Actual Behaviour

It doesn't do anything, its like i'm not even clicking on the close button.

#### Steps to reproduce the behaviour

1. Choose a movie to watch.
2. Click watch now, watch 5 seconds of the movie and close the windows.
3. Now click in the X button in the top right corner. It does not close the application. I have to 

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
```
Error in event handler: Error: ENOTEMPTY: directory not empty, rmdir 'D:\Popcorn-Time\cache\Popcorn Time\38981b8a847724de362f389a7c4cbd9b862b0a9c'
    at Object.rmdirSync (fs.js:789:3)
    at rmkidsSync (D:\Popcorn-Time\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync (D:\Popcorn-Time\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (D:\Popcorn-Time\node_modules\rimraf\rimraf.js:304:9)
    at D:\Popcorn-Time\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (D:\Popcorn-Time\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (D:\Popcorn-Time\node_modules\rimraf\rimraf.js:334:7)
    at Function.rimrafSync [as sync] (D:\Popcorn-Time\node_modules\rimraf\rimraf.js:304:9)
    at deleteFolder (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/app.js:211:10)
    at close (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/app.js:268:5)
    at NWWindow.<anonymous> (chrome-extension://hecfofbbdfadifpemejbbdcjmfmboohj/src/app/app.js:282:3)
    at NWWindow.<anonymous> (extensions::nw.Window:161:16)
```
This error is thrown everytime I click the close button.

Cheers!

**Comment by dutchy1001** [comment] 2020-10-05 06:35
Update to the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**.
If your issue is fixed plz close this or report back.

**Comment by Persei08** [comment] 2020-10-05 12:06
Duplicate of #1280

**Closed as completed by Persei08** 2020-10-05 12:06 UTC

**Comment by 1mamute** [comment] 2020-10-13 12:12
Last dev build solved this is issue for me!
