### ISSUE TITLE
Popcorn time 0.4.3 no movies load in 

### ISSUE THREAD

**Issue by balinbob1** [popcorntime/popcorntime#1323] opened 2020-04-14 11:00 UTC
Operating System Version:
 windows 10 

Popcorn Time Version:
 0.4.3

Download date:
 reinstalled it 5min ago but i used it yesterday.

#### Expected Behaviour
 show me the movies.
...

#### Actual Behaviour
 nothing it just keeps loading infinite i guess, i just see the blue circle spinning and spinning nothing happend.
...

#### Steps to reproduce the behaviour

1. ...i don't know it just happend suddenly
2. ...
3. ...
![popcorn timee](https://user-images.githubusercontent.com/63644867/79217968-88e68880-7e04-11ea-801b-ca796c9e3e25.png)

**Comment by dutchy1001** [comment] 2020-04-14 11:06
duplicate #1321

**Comment by gstapelber** [comment] 2020-04-14 11:48
> Operating System Version:
> 
> windows 10
> Popcorn Time Version:
> 
> 0.4.3
> Download date:
> 
> reinstalled it 5min ago but i used it yesterday.
> #### Expected Behaviour
> show me the movies.
> ...
> 
> #### Actual Behaviour
> nothing it just keeps loading infinite i guess, i just see the blue circle spinning and spinning nothing happend.
> ...
> 
> same is happening on my OS, no movies showing

**Comment by balinbob1** [comment] 2020-04-14 12:01
i don't really know what to do now, the thing is it worked fine yesterday night. the next morning i open it up and it just keeps loading. maybe it is just temporarily ?

**Comment by balinbob1** [comment] 2020-04-14 12:03
i just noticed that there is a new version of popcorn time: 0.4.4 ?

**Comment by balinbob1** [comment] 2020-04-14 12:04
yep the new version works with me. 
just download 0.4.4 and it will probably work

**Comment by MhadCode** [comment] 2020-04-14 12:25
Same problem here, How to download 0.4.4?

**Comment by iKenshu** [comment] 2020-04-14 12:28
You can go [here](https://ci.popcorntime.sh/job/Popcorn-Time-Desktop/409/) @MhadCode

**Comment by team-pct** [comment] 2020-04-14 12:28
https://popcorntime.app

**Comment by MhadCode** [comment] 2020-04-14 12:44
Thanks, Everyone! I appreciate ur help.

**Comment by asadmalik** [comment] 2020-04-14 13:49
Seems to be fixed. Window 10 home, latest version.

**Comment by esnover70** [comment] 2020-04-14 23:19
I have the same problem

**Comment by kiriles90** [comment] 2020-04-15 10:52
@esnover70 same solution, update to 0.4.4 or 0.2.10 if on android.

**Comment by Persei08** [comment] 2020-04-15 13:18
Duplicate of #1321

**Closed as completed** 2020-04-15 13:18 UTC
