### ISSUE TITLE
Real time synchronization in a party of viewers

### ISSUE THREAD

**Issue by filipedfr** [popcorntime/popcorntime#2380] opened 2022-01-13 22:14 UTC
**The problem**
I found it could be great to have a feature where people could create parties and then watch movies/series together with real-time synchronization. The way me and my friends tackled this is by making a countdown, which is not reliable in the long run given that sometimes people need to take a break.

**The idea**
My idea consists of implementing into popcorn-time the concept of viewer partys. A host could create a party and other viewers (like, the friends of the host) could join this party. The movie/series that the host plays, the viewers that are in the party also play and get their time synchronized: if host or a viewer pauses, then everyone's client pauses.  In times I worked around Popcorn-time and figured a way of doing this, but I used an HTTP server to receive play/pause signals from clients and distributed those signals to the other clients - this was inefficient and slow. 

**Additional context**
 I already saw a plugin on Stremio that leverages this feature and it actually performs very well. Don't know if this possibility/feature was ever considered, but I didn't looked through the issues to find the answer.

**Comment by kiriles90** [comment] 2022-01-13 23:05
Closing this because its a duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/2226 but do join the other open issue with any suggestions you might have.

**Closed as completed by kiriles90** 2022-01-13 23:05 UTC
