### ISSUE TITLE
Yarn build errors

### ISSUE THREAD

**Issue by immartian** [popcorntime/popcorntime#1366] opened 2020-04-18 15:42 UTC
Operating System Version:
<ChromeOS Linux->

Popcorn Time Version:
The most recent commit:  17adcb865976241756ae2c21f26950615060b33f 
```
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! peer dep missing: underscore@~1.8.3, required by backbone.marionette@3.5.1
npm ERR! missing: colour@latest, required by ascli@0.3.0
npm ERR! missing: optjs@latest, required by ascli@0.3.0
npm ERR! missing: vtt.js@git+https://github.com/gkatsev/vtt.js.git#vjs-v0.12.1, required by video.js@4.12.15
npm ERR! missing: http-node@github:feross/http-node#webtorrent, required by webtorrent@0.107.17

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
```

**Comment by kiriles90** [comment] 2020-10-01 00:25
@immartian does this issue still exist?

**Comment by kiriles90** [comment] 2020-10-09 19:09
@Persei08 this looks related to https://github.com/popcorn-official/popcorn-desktop/issues/1704 ? maybe just close if so, the OP doesnt seem to be coming back either.

**Comment by immartian** [comment] 2020-10-14 09:43
Yes, it persists:
```
[17:40:48] Starting 'nwjs'...
Error: Command failed: npm ls --production=true --parseable=true
npm ERR! missing: colour@latest, required by ascli@0.3.0
npm ERR! missing: optjs@latest, required by ascli@0.3.0
npm ERR! missing: vtt.js@git+https://github.com/gkatsev/vtt.js.git#vjs-v0.12.1, required by video.js@4.12.15
npm ERR! missing: http-node@github:feross/http-node#webtorrent, required by webtorrent@0.107.17

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:547:15)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true'
}
```

**Comment by pankajthekush** [comment] 2020-10-18 17:55
I am getting this, it builds eventually but does not run.
```

[23:20:09] Starting 'nwjs'...
{ Error: Command failed: npm ls --production=true --parseable=true
npm ERR! peer dep missing: underscore@~1.8.3, required by backbone.marionette@3.5.1
npm ERR! extraneous: colour@0.7.1 /home/pankaj/Documents/github/popcorn-desktop/node_modules/colour
npm ERR! extraneous: http-node@1.2.0 /home/pankaj/Documents/github/popcorn-desktop/node_modules/http-node
npm ERR! extraneous: optjs@3.2.2 /home/pankaj/Documents/github/popcorn-desktop/node_modules/optjs
npm ERR! extraneous: vtt.js@0.12.1 /home/pankaj/Documents/github/popcorn-desktop/node_modules/vtt.js
npm ERR! peer dep missing: bufferutil@^4.0.1, required by ws@7.2.1
npm ERR! peer dep missing: utf-8-validate@^5.0.2, required by ws@7.2.1
npm ERR! missing: colour@latest, required by ascli@0.3.0
npm ERR! missing: optjs@latest, required by ascli@0.3.0
npm ERR! missing: vtt.js@git+https://github.com/gkatsev/vtt.js.git#vjs-v0.12.1, required by video.js@4.12.15
npm ERR! missing: http-node@github:feross/http-node#webtorrent, required by webtorrent@0.107.17

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm ls --production=true --parseable=true' }
Received status code 504: https://popcorntime.app/version.json
[23:21:22] Finished 'nwjs' after 1.2 min
[23:21:22] Starting '<anonymous>'...
[23:21:22] Finished '<anonymous>' after 180 μs
[23:21:22] Finished 'build' after 1.25 min
Done in 75.98s.

```
```
[pankaj:popcorn-desktop]$ yarn start
yarn run v1.22.10
$ gulp run
[23:26:06] Using gulpfile ~/Documents/github/popcorn-desktop/gulpfile.js
[23:26:06] Starting 'run'...
Running linux64 from cache
linux64 is not available in cache. Try running `gulp build` beforehand
[23:26:06] 'run' errored after 5.87 ms
[23:26:06] Error: spawn cache/0.44.5-sdk/linux64/nw ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[pankaj:popcorn-desktop]$ 

```

**Comment by kiriles90** [comment] 2020-10-18 20:19
@pankajthekush have you checked https://github.com/popcorn-official/popcorn-desktop/issues/1704 ?

**Comment by pankajthekush** [comment] 2020-10-19 03:45
The main issue was most probably from 
`Received status code 504: https://popcorntime.app/version.json`
it was trying to download njws sdk from [official website](get.popcorntime.app) and was not able to download may because of some network issue or the website was not up in first place, is it possible that you pull njws sdk from github somewhere , in case website is blocked in given region or not up ?

It is working now.
Thank You.

**Comment by kiriles90** [comment] 2020-10-19 05:29
Oh sorry my bad, I should have read your log more carefully. At least the issue is solved now, great.

About adding the custom nwjs Popcorn Time uses somewhere on github, I'm not sure if that can be done or might cause issues @team-pct @Persei08 your thoughts?

**Comment by Persei08** [comment] 2020-10-22 20:36
i have the issue too this evening.

**Comment by Persei08** [comment] 2020-10-30 15:14
I close this issue.

The `npm ls --production=true --parseable=true` error isn't important here, it's just bugging because the command return some errors about missing colour, optjs, vtt.js, http-node ... but else it doesn't bug the app by itself.

and the other error `Received status code 504: https://popcorntime.app/version.json` are server issues which can happens from time to time.

**Closed as completed by Persei08** 2020-10-30 15:14 UTC
