### ISSUE TITLE
Not able to install through homebrew

### ISSUE THREAD

**Issue by Base29** [popcorntime/popcorntime#1972] opened 2021-01-05 20:12 UTC
Operating System Version:
OS X 11.1

Popcorn Time Version:
0.4.4

Download date:

Download url (optional):

#### Expected Behaviour
Expected to download and install with homebrew
...

#### Actual Behaviour
Wasn't able to download and install with homebrew please refer to the attached screenshot for the error I receive. 
...

#### Steps to reproduce the behaviour

brew tap popcorn-official/popcorn-desktop https://github.com/popcorn-official/popcorn-desktop.git
brew install --cask popcorn-time

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

![image](https://user-images.githubusercontent.com/5220908/103694001-061de300-4fbc-11eb-81a9-dc3b209ad78e.png)

**Comment by kiriles90** [comment] 2021-01-05 20:53
The screenshot you linked shows what the problem is on the last line. You cant connect to get.popcorntime.app and instead returns a 443 error. Solve that and it will work.  

Closing this since its not an issue with the app.

**Closed as completed by kiriles90** 2021-01-05 20:53 UTC
