### ISSUE TITLE
Two errors

### ISSUE THREAD

**Issue by xrposto** [popcorntime/popcorntime#1544] opened 2020-07-01 20:50 UTC
Operating System Version:
Windows 8.1

Popcorn Time Version:
4.4

I find two errors:
1- I cannot run Torrents searched on other sites
2- I can't close the program (this happens from the moment I start a movie, before yes)

In the previous version, 3.10, everything worked well for me, but now when I reinstall it, it does not connect to the server, so neither the list of movies nor the covers appear, nothing, besides that all the time it tells me that I have to update to version 4.4

**Comment by dutchy1001** [comment] 2020-07-02 13:59
I'm not sure about your first issue.

Your second issue should be fixed in the latest dev build, get it **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/424/)**. 

The reason version 3.10 doesn't work anymore is due to a change from the torrent site(s). Apparently the links/connections to those site(s) have changed. This was out of controle of PCT but quickly fixed in the newer version.

**Comment by xrposto** [comment] 2020-07-02 16:27
Thank you very much for answering...
I just downloaded and installed that latest version you sent me, and indeed the second error, of not being able to close the program, was solved. Thank you very much.
Regarding the other error, of not being able to run torrents searched on other sites, that error continues, and it seems strange to me, because in version 3.10, I can do it.
Could you find a solution to that?
It is something that I use a lot.
Many thanks!!!

**Comment by dutchy1001** [comment] 2020-07-02 17:00
Unfortunately I'm not a coder. I try to help out to solve issue's that are not related to coding so the devs don't have to waste their time answering those questions.
Your other issue have to be looked at by one of the devs unfortunately.

**Comment by xrposto** [comment] 2020-07-02 17:18
ok, look, i just tried again and left it for a long time, and the movie started to run.
Either way, the program began to consume all my resources, RAM, and Rigid Disk, something that had never happened to me, the computer stopped working and I had to turn it off.
I'm going to do some research on that topic and write to you again.
Thank you very much for your interest and your help.

**Comment by Persei08** [comment] 2020-09-26 15:54
Please try last dev build: https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/

It should improve stability a bit and should fix the closing issue

**Comment by kiriles90** [comment] 2020-09-28 20:23
the original two issues are fixed

> Either way, the program began to consume all my resources, RAM, and Rigid Disk, something that had never happened to me, the computer stopped working and I had to turn it off.

is duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1373

@xrposto @Persei08 please close this

**Closed as completed** 2020-09-28 20:50 UTC
