### ISSUE TITLE
Homebrew not working

### ISSUE THREAD

**Issue by Jalvcl** [popcorntime/popcorntime#2095] opened 2021-04-11 19:35 UTC
Operating System Version:
OS X 10.13

Download url (optional):
Homebrew 

#### Expected Behaviour
Install popcorn-time
...

#### Actual Behaviour
Updating Homebrew...
==> Downloading https://get.popcorntime.app/build/Popcorn-Time-0.4.4.pkg
==> Downloading from https://medium.com/@getpopcornapp/goodbye-popcorn-time-93f890b8c9f4

curl: (22) The requested URL returned error: 410
Error: Download failed on Cask 'popcorn-time' with message: Download failed: https://get.popcorntime.app/build/Popcorn-Time-0.4.4.pkg

**Comment by kiriles90** [comment] 2021-04-11 20:27
It doesnt work because popcorntime.app was taken down. Check the subreddit for more info.

Closing this because its basically duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/2090

**Closed as completed by kiriles90** 2021-04-11 20:27 UTC

**Comment by Jalvcl** [comment] 2021-04-11 20:39
> It doesnt work because popcorntime.app was taken down. Check the subreddit for more info.
> 
> Closing this because its basically duplicate of #2090

thanks
