### ISSUE TITLE
Startup and OS interaction cause popcorntime and the whole OS to be unresponsive for seconds

### ISSUE THREAD

**Issue by giorgiolorini** [popcorntime/popcorntime#1432] opened 2020-04-30 11:34 UTC
Operating System Version:
OS X Mojave 10.14.5

Popcorn Time Version:
0.4.4-0

#### Expected Behaviour
Opening up and interacting smoothly with the OS.

#### Actual Behaviour
On startup the system gets frozen for more or less 10 seconds than it starts working correctly.
Every interaction with the OS UI (like startup from dock icon, custom subtitles selection or opening cache directory from settings tab) causes Popcorntime to be unresponsive for some seconds. This behaviour is new, not happening in older versions.

**Comment by kiriles90** [comment] 2020-10-01 00:30
@Persei08 duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/962, close please

**Closed as completed** 2020-10-01 05:28 UTC
