### ISSUE TITLE
anyone else have problems with subtitles?

### ISSUE THREAD

**Issue by MooseWay08** [popcorntime/popcorntime#1302] opened 2020-04-10 22:11 UTC
Hello, I have been using popcorn time since last year (I don't remember which was the first version I downloaded, to be honest) but since I have version 4.1 and 4.3 I have problems with subtitles (I can only use them if I download them previously and load them. What happens to someone else?

**Comment by kiriles90** [comment] 2020-04-11 10:01
Duplicate https://github.com/popcorn-official/popcorn-desktop/issues/1252 and fixed in https://ci.popcorntime.app/job/Popcorn-Time-Desktop/407/

(you still need to login, this depends on opensubtitles if they ever lift this 'everyone needs to login for the API' limitation again)

**Comment by Persei08** [comment] 2020-04-12 22:41
Duplicate of #1252

**Closed as completed by Persei08** 2020-04-12 22:41 UTC
