### ISSUE TITLE
App launch crash

### ISSUE THREAD

**Issue by lab4here** [popcorntime/popcorntime#2662] opened 2022-11-23 20:20 UTC
Operating System Version:
macOS 13.0.1 Mchip

Popcorn Time Version:

0.4.9 - a14488b2

Download date:
november

Download url:
(https://popcorn-time.ga/build-ru/)

#### Expected Behaviour
Launch app and use

#### Actual Behaviour

after firewall access granted
app launch then crushes 
it happens 2-3 times before getting stable

#### Steps to reproduce the behaviour

1. launch app
2. garant firewall access
3.  app starts up 
4. It crush at showing interface 

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)

[macos13.0.1.Mchip-crash.pdf](https://github.com/popcorn-official/popcorn-desktop/files/10078940/macos13.0.1.Mchip-crash.pdf)
<img width="604" alt="Capture d’écran 2022-11-23 à 21 10 23" src="https://user-images.githubusercontent.com/118193011/203639088-eccffe7b-6451-464e-9c30-7d5372a16554.png">

**Comment by kiriles90** [comment] 2022-11-23 20:45
Duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/2658 (and many more). Same answer, its related to NW.js which needs to be updated but there are problems. Follow the NW.js issue for more.

**Closed as completed by kiriles90** 2022-11-23 20:45 UTC
