### ISSUE TITLE
Custom subtitles not being displayed when playing on Chromecast or SmartTV

### ISSUE THREAD

**Issue by wlmirand** [popcorntime/popcorntime#385] opened 2016-12-05 00:00 UTC
Operating System Version:
Manjaro Linux

Popcorn Time Version:
3.10

Download date:
Dec 4th, 2016

#### Expected Behaviour
Display custom subtitles on Chromecast or SmartTV
...

#### Actual Behaviour
Custom subtitles are not displayed

#### Steps to reproduce the behaviour

1. Set the default subtitle language as Brazilian Portuguese
2. Find the new Independence Day movie (which does not have brazilian portuguese subtitles)
3. Play it on Chromecast or SmartTV
4. Since this movie does not have subtitles, the Popcorn app will display a message to drag/drop a subtitle file to the player window.
5. I downloaded a subtitle from the internet, which works when I play using Butter.
6. When I drag and drop this subtitle file (SRT) to player window, while playing on Chromecast or SmartTV, the subtitles are not displayed.

Thanks

**Comment by jordanjamous** [comment] 2016-12-11 08:45
Same issue on windows 10, english subtitles, although I am watching kinda old movies and when I checked cache directory I found subtitles are already there!
Sometimes, when I watch a series, it works fine. 
v 0.3.10 Beta

**Comment by ChrisAlderson** [comment] 2016-12-13 13:31
Duplicate of #196

**Closed as completed by ChrisAlderson** 2016-12-13 13:31 UTC
