### ISSUE TITLE
Close button icon is not working 

### ISSUE THREAD

**Issue by shwetachauhan20494** [popcorntime/popcorntime#1677] opened 2020-09-09 16:13 UTC
Operating System Version:
win 10

Popcorn Time Version:
4.4

Download date:
a month ago

Download url (optional):
download from popcorn site

#### Expected Behaviour
When I press close button app should be closed.
...

#### Actual Behaviour
 I should be closed but stays as it is for closing it I actually go to task manager and end the popcorn process instead.
...

#### Steps to reproduce the behaviour

1. ...Open app
2. ...click on close button
3. ...See if it is closed or not

#### Screenshot of error from developer console (optional)

![Button probem](https://user-images.githubusercontent.com/36619261/92624757-7efa8000-f2e5-11ea-9616-37d16ee72953.PNG)

**Comment by dutchy1001** [comment] 2020-09-09 17:01
You could have read the pinned topic  on top of the issue page.
If that is to much to do then  update to the latest dev build from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**

**Comment by Persei08** [comment] 2020-09-11 15:16
Duplicate of #1280

**Closed as completed by Persei08** 2020-09-11 15:16 UTC
