### ISSUE TITLE
feature request: subtitles ui for external players

### ISSUE THREAD

**Issue by cghislai** [popcorntime/popcorntime#1332] opened 2020-04-14 21:48 UTC
possible duplicate: https://github.com/popcorn-official/popcorn-desktop/issues/942 

Operating System Version: up to date linux

Popcorn Time Version:  0.4.4

Download date: today

#### Expected Behaviour
I would like to be able to download subtitles using popcorn time ui when playing in an external player.

#### Actual Behaviour
Only in the embedded player Im able to choose a language to download subtitles from. (or using players which bring an ui to do so themselves).

It would be nice to have a subtitles menu either on the episode page (next to quality for instance), or the status page displayed when the external player is open.

**Comment by kiriles90** [comment] 2020-09-26 16:02
@Persei08 duplicate of #1540 , close please

**Comment by kiriles90** [comment] 2020-09-26 20:38
@Persei08 duplicate of #1540 , close please

**Comment by pedronn84** [comment] 2020-10-21 17:53
Please, make this happen. I can see movies with portuguese subtitles while casting to my tv, but tvshows not, because in movies it's possible to choose the subtitles we want due that subtitle menu, but in tvshows no, so this would be excellent

**Comment by dutchy1001** [comment] 2020-10-21 20:03
@pedronn84 
Have you set the default subtitle in the settings?

**Comment by pedronn84** [comment] 2020-10-21 20:09
> @pedronn84
> Have you set the default subtitle in the settings?

Yep, but for some reason, always appears the english one, dunno why...

**Comment by dutchy1001** [comment] 2020-10-21 21:02
I use an external player but when changing default subs to Dutch (Nederlands) from English it will give me the Dutch ones then.

Have you updated to the latest dev build (from **[here](https://ci.popcorntime.app/job/Popcorn-Time-Desktop/lastStableBuild/)**)

**Comment by pedronn84** [comment] 2020-10-21 21:19
Well, in the application everything it's done right, the problem it's when I cast to my tv. When I cast a movie, the subs are correct, but when I cast some episode (anyone), the subs always appears in english...

I'm going to download the latest dev from that link, then I see what happens 👍

**Comment by pedronn84** [comment] 2020-10-21 22:43
Oh yeah, now we are talking the same language. I updated to the latest dev build and the default subs, which is portuguese in my case, already appears in my tv!

Dank u wel, mijn vriend dutchy, really appreciate 👍

**Closed as completed** 2021-10-24 00:45 UTC
