### ISSUE TITLE
Popcorn Time Won't Close

### ISSUE THREAD

**Issue by transamgt35** [popcorntime/popcorntime#1388] opened 2020-04-22 10:01 UTC
Operating System Version:
Windows 10

Popcorn Time Version:
0.4.4-0

Download date:
4/23/2020

#### Expected Behaviour
I thought when you click the "X" on the upper right hand corner of the app window it would close.
...

#### Actual Behaviour
I click the "X" on the upper right hand corner of the app window and it doesn't close the app. It just sits there.
...

#### Steps to reproduce the behaviour

1. ...Open the Popcorn Time app
2. ...Start watching a movie.
3. ...Click "X" on the upper right hand corner of the app window.

**Comment by dutchy1001** [comment] 2020-04-22 10:44
Duplicate of #1280 #1354 

Try to search before posting an issue that already has been mentioned a few times

**Comment by Persei08** [comment] 2020-04-26 18:21
Please search for similar issues before creating new ones.
Duplicate of #1280

**Closed as completed by Persei08** 2020-04-26 18:21 UTC
