### ISSUE TITLE
Popcorn Time not logging into Trakt on Mac

### ISSUE THREAD

**Issue by jnoutinen** [popcorntime/popcorntime#766] opened 2018-04-23 02:03 UTC
Operating System Version:
OS X 10.13.4

Popcorn Time Version:
3.10

Download date:
April 22, 2018

#### Expected Behaviour
Connect to and sync my Trakt account

#### Actual Behaviour
After logging in and clicking "Connect to Trakt" and selecting Yes, the window briefly provides me with a PIN and then closes without connecting to the account. Can click the login button again and re-allow my account and get same outcome. Then if I leave Settings and return, the login button opens a blank screen.

#### Steps to reproduce the behaviour
1. Start Popcorn Time 3.10 on Mac
2. Go to Settings
3. Click "Connect to Trakt"
4. Login to Trakt & click "Yes" to allow connection
5. Login window closes automatically without connecting to Trakt

![untitled](https://user-images.githubusercontent.com/38638453/39103459-c93c93c2-4678-11e8-878a-ad640434ef85.gif)

**Comment by Persei08** [comment] 2018-04-24 18:35
Dupe of #708 
Should be working with dev build 277 : https://ci.popcorntime.sh/view/All/job/Popcorn-Time-Desktop/

**Comment by jnoutinen** [comment] 2018-04-24 23:08
Gotcha. Sorry I saw #708 but didn't realize it applied to OS X too. Thanks @Persei08!

**Comment by ChrisAlderson** [comment] 2018-04-28 18:55
Duplicate of #708

**Closed as completed by ChrisAlderson** 2018-04-28 18:55 UTC

**Comment by PrimaSorte** [comment] 2019-02-11 01:18
Sorry to up this thread from long ago, I'm trying to download from the link posted and... well... it doesn't let me download! Apparently it says "Connection error" or something like that, I don't get why

**Comment by heyitsbea** [comment] 2019-03-01 14:16
I've been trying to use the link as well, but it fails due to network error.. Does anyone know a solution?
