### ISSUE TITLE
Automatic play uses wrong torrent

### ISSUE THREAD

**Issue by LordzShadow** [popcorntime/popcorntime#2208] opened 2021-06-14 16:19 UTC
Operating System Version: Windows 10

Popcorn Time Version: 0.4.4

Download date: 2021/06/13

Download url (optional): http://popcorn-ru.tk/build/
I also tried : https://github.com/popcorn-official/popcorn-desktop/actions/runs/930274849

#### Expected Behaviour
Play next episode automatically after finishing an episode.

#### Actual Behaviour
The torrent isn't updated(title and everything else is) and the wrong episode is played.
My best bet is that it has something to do with cache not updating or something.
Probably should mention that I have "Clear Cache Folder after closing the app?" disabled.

I would try to find the bug myself in the code but I'm not familiar with the codebase.

#### Steps to reproduce the behaviour

1. Start playing an episode
2. Go to the end of the episode
3. Press play now
4. The title and torrent do not match

#### Screenshot(s) of issue or error(s) logs of developer console
Console didn't have any errors except for a watchlist one(not really sure what that is)
![image](https://user-images.githubusercontent.com/44734448/121924756-daf6a700-cd44-11eb-9f19-492be71ab925.png)

**Comment by LordzShadow** [comment] 2021-06-14 16:36
For example with Rick and Morty Season 4, whatever episode you start with, the next episode that plays is S4E9.

**Comment by kiriles90** [comment] 2021-06-14 19:39
Its because that's a full season torrent. @ivan1986 made some changes for the 'Watch now' button to work with them correctly but it seems the same changes weren't implemented in https://github.com/popcorn-official/popcorn-desktop/pull/2048 when it was merged to fix the 'Play next episode automatically' feature. Ivan any ideas or are there issues with doing the same here?

**Comment by ivan1986** [comment] 2021-06-14 19:53
@kiriles90 0.4.4 it's ok - fix not exist, but if bug reproduc in last build...

**Comment by kiriles90** [comment] 2021-06-14 20:01
@ivan1986 lol I edited your comments instead of replying, damn painkillers.. :D Yeah I can reproduce it using the dev branch as it is right now. I dont know if #2204 has anything to do with this, but I'm testing that one right now so we can merge.

**Comment by ivan1986** [comment] 2021-06-14 20:05
#2204 not do anything with selecting episodes, ok, need fix play next episode - support files

**Comment by kiriles90** [comment] 2021-06-14 20:08
Yeah figured, either way testing right now so we can merge. 
Play next episode works btw, just doesnt work with full season torrents it selects the wrong and always same file, #2048 from above must need some edits like Watch now needed because this is pretty much the same issue that one had.

**Comment by kiriles90** [comment] 2021-06-14 20:30
Merged #2208 too, thanks Ivan.

**Closed as completed** 2021-06-14 20:29 UTC
Labels: bug
