### ISSUE TITLE
watch now and download not working 2

### ISSUE THREAD

**Issue by CharlotteRicca** [popcorntime/popcorntime#1803] opened 2020-11-09 16:46 UTC
Operating System Version:
OS X 10.11

Popcorn Time Version:
**the latest version**

Download date:
today at 4pm UK time

Download url (optional):
https://popcorntime.app/mac

#### Expected Behaviour
I have used for a months now with no problems
...

#### Actual Behaviour
it won't let me watch or download. When I click the buttons nothing happens
...

#### Steps to reproduce the behaviour

1. ...click on watch now
2. ...click on download
3. ...

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
<img width="1482" alt="Screenshot 2020-11-09 at 16 45 28" src="https://user-images.githubusercontent.com/74201712/98570154-04c98600-22ab-11eb-90f1-8fe95c3dd024.png">

**Comment by CharlotteRicca** [comment] 2020-11-09 16:46
i hope I have provided enough info this time

**Comment by dutchy1001** [comment] 2020-11-09 16:53
thx but you didn't have to create a new issue, just edited the other 😛. (please close that one)

The website version might be outdated, but if you follow the link in the other post you will be directed to the latest build. Please update to that version (choose : Popcorn-Time-0.4.4_osx64.zip).
On my pc (w10) the serie you mention is working fine

**Comment by kiriles90** [comment] 2020-11-09 16:54
You did but this issue is duplicate of #1280. Same solution, update to the latest dev build from ci.popcorntime.app (441 at the moment)

**Closed as completed by kiriles90** 2020-11-09 16:54 UTC

**Comment by CharlotteRicca** [comment] 2020-11-09 17:21
I've followed that link and it seems to be the same version as the one I already had. However, I have reinstalled it.
The 'watch now' works now, but I then get a VPN message (attached). I have a VPN already.
And it doesn't then connect.
I have tried again and now it just says 'connecting' but nothing happens 

Persei08 edit: Removing personal details

**Comment by kiriles90** [comment] 2020-11-09 17:24
You can disable the VPN ad in the settings. Disable the 'enable VPN' checkbox. But for if something connects or not, thats not up to Popcorn Time. It depends if it has any seeds. Hover the red/yellow/green dot on the top right of the movie/episode detail screen and check.

**Comment by CharlotteRicca** [comment] 2020-11-09 17:32
I have disabled VPN but does this mean I am now not protected?
Also, I don't know what seeds are! Sorry. 
I hover over the red button and it says seeds: 1 peers: 0
is this good or bad?

**Comment by kiriles90** [comment] 2020-11-09 17:42
> I have disabled VPN but does this mean I am now not protected?  

No you are protected by your own VPN. This just disables the VPN ad/warning in Popcorn Time.

> I hover over the red button and it says seeds: 1 peers: 0
is this good or bad?

Bad :) That's why it wont connect. Use the torrent collection and find some other torrent with more of them. Usually full season torrents have the best seeds if its about older seasons/shows.

**Comment by dutchy1001** [comment] 2020-11-09 18:52
I hope the IP and City are through a VPN, if not take the pic down or blank those details out just to be safe.

**Comment by the-soap** [comment] 2020-11-19 09:23
> Operating System Version:
> OS X 10.11
> 
> Popcorn Time Version:
> **the latest version**
> 
> Download date:
> today at 4pm UK time
> 
> Download url (optional):
> https://popcorntime.app/mac
> 
> #### Expected Behaviour
> I have used for a months now with no problems
> ...
> 
> #### Actual Behaviour
> it won't let me watch or download. When I click the buttons nothing happens
> ...
> 
> #### Steps to reproduce the behaviour
> 1. ...click on watch now
> 2. ...click on download
> 3. ...
> 
> #### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) (recommended)
> <img alt="Screenshot 2020-11-09 at 16 45 28" width="1482" src="https://user-images.githubusercontent.com/74201712/98570154-04c98600-22ab-11eb-90f1-8fe95c3dd024.png">

same issue here..... https://github.com/popcorn-official/popcorn-desktop/issues/1844

**Comment by Persei08** [comment] 2020-11-20 00:25
@the-soap it's a different issue. In your issue PCT crash. 
Here it's about the "watch now" button (which is already fixed in latest dev builds) and the fact the torrent have low health.
