### ISSUE TITLE
Chromecast displaying scroll bar

### ISSUE THREAD

**Issue by eslimaf** [popcorntime/popcorntime#199] opened 2016-07-02 16:45 UTC
Operating System Version: OS X 10.11

Popcorn Time Version: 0.3.9

Download date: 6-21-2016

#### Expected Behaviour

No scroll bar should be visible while casting

...
#### Actual Behaviour

Scroll bar is shown at the bottom of the screen

...
#### Steps to reproduce the behaviour

1. Choose a long title file
2. Play to Chromecast

![IMAGE](http://i.imgur.com/X4Inf1j.jpg)

**Comment by ChrisAlderson** [comment] 2016-10-21 23:10
I can confirm this issue with a 21 inch monitor. #218 and #200 partially solve this issue, but in specific environments with a certain screen size. I'm closing both PR's since they do not solve the underlying issue. 

I think the underlying issue has nothing to do with the code of Popcorn Time. I think it has something to do with the code of `[chromecasts-pct](https://github.com/mafintosh/chromecasts)`.

**Comment by team-pct** [comment] 2016-10-27 11:04
fixed on 8701ed6

**Closed as completed by team-pct** 2016-10-27 11:04 UTC
Labels: help wanted
