### ISSUE TITLE
sci-fi

### ISSUE THREAD

**Issue by ethemozer** [popcorntime/popcorntime#201] opened 2016-07-03 17:18 UTC
Operating System Version:

Popcorn Time Version:

Download date:

#### Expected Behaviour

...
when you try to sort movie for sci-fi 
#### Actual Behaviour

...
there is no movie
#### Steps to reproduce the behaviour

1. ...
2. ...
3. ...

**Comment by ChrisAlderson** [comment] 2016-07-03 17:20
Duplicate of #160

**Closed as completed** 2016-07-03 21:06 UTC
