### ISSUE TITLE
Black screen win 8.1

### ISSUE THREAD

**Issue by biustech** [popcorntime/popcorntime#1380] opened 2020-04-20 21:08 UTC
Operating System Version:
WIN 8.1 Pro x64

Popcorn Time Version:
from 4.3 - latest 4.4 both 32 and 64 bits versions

Download date:
20.04.20

#### Expected Behaviour
load main window and ask me to accept the terms
...

#### Actual Behaviour
black screen no buttons, no text
...

**Comment by Persei08** [comment] 2020-04-20 22:25
Duplicate of #1347. Please search before opening new report

**Closed as completed by Persei08** 2020-04-20 22:25 UTC
