### ISSUE TITLE
High RAM Usage

### ISSUE THREAD

**Issue by JoecMit** [popcorntime/popcorntime#1335] opened 2020-04-14 23:53 UTC
Operating System Version: Windows 10 Pro x64

Popcorn Time Version: 0,4,4

Download date: 14/04/2020

#### Expected Behaviour

Normal RAM usage.

#### Actual Behaviour

After a few minutes, almost an hour the RAM usage get over 14 GB (i got 16GB), so the entire PC starts to be "laggy", the app doesn't respond, the **X** for closing just don't work neither the keyboard shortcuts, like hitting **ESC**.

#### Steps to reproduce the behaviour

1. Start the app
2. Watch anything
3. Wait some time

**Comment by psypersky** [comment] 2020-04-15 01:18
Same here, also nwjs process is using 126% CPU just by opening pocorn

**Comment by kiriles90** [comment] 2020-04-15 10:47
@psypersky macOS should really change that lol.. wth does '126%'  even mean? Did the cpu get superpowers? :p  
Anyway, try Settings > Security & Privacy > Accessibility and uncheck Popcorn Time if you want and see if it helps.

**Comment by Persei08** [comment] 2020-04-15 12:44
@JoecMit please don't create duplicate issue

Duplicate of #1299

**Closed as completed by Persei08** 2020-04-15 12:44 UTC

**Comment by psypersky** [comment] 2020-04-15 16:51
@kiriles90 that's just the way OSX puts your processing usage https://apple.stackexchange.com/questions/5329/what-does-it-mean-when-a-cpu-exceeds-of-cores-x-100.

Just putting my solution, my PT wasn't able to download the new update and nw.js was going crazy using a ton of processing, I deleted PT and downloaded the last one from the page, that fixed the issue.

**Comment by kiriles90** [comment] 2020-04-15 19:29
Yeah I know what they mean by it.. just saying it doesnt make much sense even if you have multiple cores (everything does this days..) Its still the same cpu.. ;)
