### ISSUE TITLE
[M1] 0.4.9 Crashing on MacOS on startup multiple times and unstable

### ISSUE THREAD

**Issue by pawisoon** [popcorntime/popcorntime#2659] opened 2022-11-20 18:04 UTC
Operating System Version:
MacOS 13.0.1 (22A400)
M1 Pro, Macbook 14"

Popcorn Time Version:
0.4.9

Download date:
Recently

Download url:
https://github.com/popcorn-official/popcorn-desktop/releases/download/v0.4.9/Popcorn-Time-0.4.9.pkg

#### Expected Behaviour
App should open normally and do not crash on startup or first action within app.

#### Actual Behaviour
App crashes multiple times on startup, sometimes works a moment until I take any action in app to crash again.

#### Steps to reproduce the behaviour
1. Install app
2. Open app
3. Crash. Re-open. Crash again. Re-open. Crash again. Re-open, then window stays on and one action and app crashes again.

#### Screenshot(s) of issue or error(s) logs of developer console (Windows/Linux: F12, MacOS: ⌘ + 0 ... then 'console' tab) 
Log attached: 
[log.txt](https://github.com/popcorn-official/popcorn-desktop/files/10050361/log.txt)

**Comment by kiriles90** [comment] 2022-11-20 21:08
Duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/2658 (and many more). Same answer, its related to NW.js which needs to be updated but there are problems. Follow the NW.js issue for more.

**Closed as completed by kiriles90** 2022-11-20 21:08 UTC
