### ISSUE TITLE
yarn dist not working on windows

### ISSUE THREAD

**Issue by riclas** [popcorntime/popcorntime#1719] opened 2020-10-03 00:27 UTC
i get the following error when building either win32 or 64:

[01:20:43] 'prepareUpdater:win' errored after 12 ms
[01:20:43] Error: File not found with singular glob: C:\Users\...\popcorn-desktop\build\Popcorn-Tim
e-0.4.4-win64-Setup.exe (if this was purposeful, use `allowEmpty` option)

i can test changing the gulpfile if needed

**Comment by kiriles90** [comment] 2020-10-03 02:05
> i can test changing the gulpfile if needed

@riclas ofc, you can make a PR if you want
also this is duplicate of https://github.com/popcorn-official/popcorn-desktop/issues/1704 please close

**Comment by Persei08** [comment] 2020-10-03 05:32
Duplicate of #1704

**Closed as completed by Persei08** 2020-10-03 05:32 UTC

**Comment by riclas** [comment] 2020-10-03 17:04
i meant that if someone can tell me what to put on the gulp file to add that allowempty i can test it :D
